### ISSUE TITLE
Width does not automatically extended 

### ISSUE THREAD

**Issue by w123dog** [wenzhixin/multiple-select#102]
```
$('.selectList').multipleSelect({
            filter: true
});
```
![qq20140618165111](https://cloud.githubusercontent.com/assets/836445/3311560/255b4286-f6c6-11e3-896b-73d53308ab89.png)

**Comment by wenzhixin** [comment]
just like @michaeladamek said: http://jsfiddle.net/wenyi/knbdm5hu/16/
ref #255
