### ISSUE TITLE
Does multipleselect work inside a jQuery dialog?

### ISSUE THREAD

**Issue by mahanhz** [wenzhixin/multiple-select#109]
When I create a multipleselect inside a jQuery dialog the checkboxes don't check, but the text of the option selected appears in the text field.

![multipleselect_inside_jquery_dialog1](https://cloud.githubusercontent.com/assets/8124705/3538689/33c2228a-0833-11e4-83a3-9ef64c189aa0.png)

If I select another checkbox (once again checkbox doesn't check) then it simply overrides the previous value, preventing me from selecting multiple options.

![multipleselect_inside_jquery_dialog2](https://cloud.githubusercontent.com/assets/8124705/3538697/61483848-0833-11e4-8b3b-b203a814d886.png)

I am using the latest version.

**Comment by menahem** [comment]
it's look like it's z-index issue. try to play with it.
you can find solution that may fit for you [here](https://github.com/wenzhixin/multiple-select/issues/18)

Hope it help...
