### ISSUE TITLE
Very slow when the list is having more than 500 items.

### ISSUE THREAD

**Issue by deepakipr** [wenzhixin/multiple-select#113]
Very slow when the list is having more than 500 items.
Its is taking too much time (6-9 seconds) to list the items in the drop-down.

Im seeing this issue particularly in IE8. Is there any way to address this issue.

Thanks in advance.

**Comment by mjmgooch** [comment]
+1

**Comment by wenzhixin** [comment]
Same with #66

**Comment by sreenivasanac** [comment]
+1
