### ISSUE TITLE
calling setSelects function during onload event

### ISSUE THREAD

**Issue by prithvirajan** [wenzhixin/multiple-select#117]
Hi,
I'm trying to call setSelects function during page load (need to load dynamic content). But it doesn't select anything. But when an alert is placed inside the function it works perfectly. Please find the code which i'm using for now and help me to resolve this issue.

HTML 

```
<body onload="updateValues()">
<div id="mulcont">
<select id="msx" multiple='multiple' class='form-control' name="msx">
</div>
</body>
```

Js

```
$(document).ready(function(e) {
    $(function() {
                $("#msx").multipleSelect({
                        placeholder:"Select Multiple Values",
                        filter:true,
                        onClose: function() {
                         }
                    });
              });      
 });    

function updateValues(){
var data_arr=[23,34,54];
alert(data_arr);
$("#mulcont").find('select').multipleSelect('setSelects',data_arr);
}
```

**Comment by richarddsouzabluemarksoft** [comment]
Hi. 

   I am trying to setSelects value by passing an array of strings to it. But only the first value is getting selected in the dropdown. 

$("#ddlCity").multipleSelect({
            filter: true,
            placeholder: "None selected",
            width: "100%"
        });

$("#ddlCity").multipleSelect('setSelects', selectedCities); //selectedCities contains an array of string.

When I pass a hardcoded array then the drop down selection is working fine, but when I pass an array variable than only the first index value gets selected.
If i pass data as 
$("#ddlCity").multipleSelect('setSelects', ["New York", "London"]);

it seems to work.
