### ISSUE TITLE
Loses previous selection on chosing second dropdown

### ISSUE THREAD

**Issue by prithvirajan** [wenzhixin/multiple-select#118]
Hi,
I'm using two drop downs in the same page which requires only single selection. But my problem is when i choose option from second drop down the first one loses its selection in radio button and selected value appears fine. Here is my copy of my code which works fine when kept separately, can you tell me what goes wrong:

 <link rel="stylesheet" href="http://wenzhixin.net.cn/p/multiple-select/multiple-select.css" />
<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="http://wenzhixin.net.cn/p/multiple-select/jquery.multiple.select.js"></script>

    $(function() {
        $("#msx").multipleSelect({
            width: '100%',
            placeholder: "Select Multiple Values",
            filter: true,
            single:true
        });

        $("#msy").multipleSelect({
            width: '100%',
            placeholder: "Select Multiple Values",
            filter: true,
            single:true
        });
    });

    <select id="msx" multiple="multiple" class="form-control" name="msx">
        <option value="23">23</option>
        <option value="34">34</option>
        <option value="54">54</option>
        <option value="64">64</option>
    </select>

    <select id="msy" multiple="multiple" class="form-control" name="msy">
        <option value="23">23</option>
        <option value="34">34</option>
        <option value="54">54</option>
        <option value="64">64</option>
    </select>

**Comment by wenzhixin** [comment]
Fixed in the latest version.
