### ISSUE TITLE
Unable to get property 'prop' of undefined or null referance

### ISSUE THREAD

**Issue by rahuldayal** [wenzhixin/multiple-select#120]
Error Screenshot: ![capture](https://cloud.githubusercontent.com/assets/8329420/3778156/64d8af14-196e-11e4-9e5c-e7833bf9c51f.PNG)
i ahve form in which i used multiple select 4 times. when i am reading and setting value from database using setSelects function this is giving above error.
some time it works but some time it give error

**Comment by DzmVasileusky** [comment]
This happens when you call the method with jquery selector
`$('.multi-select').multipleSelect('setSelects', [optionVal]);`

Instead of you should use it like that
`var select = $('.multi-select').multipleSelect();`
`select.multipleSelect('setSelects', [optionVal]);`

**Comment by wenzhixin** [comment]
Just like @DzmVasileusky said.
