### ISSUE TITLE
Invert if blocks in update function

### ISSUE THREAD

**Issue by mystcreater** [wenzhixin/multiple-select#122]
Hi,

First, thank you for this great product!

As you can see below, I've inverted the two if blocks. 

![block](https://cloud.githubusercontent.com/assets/230587/3803396/fd13f88a-1c19-11e4-85fd-d60ed8572b5a.png)

Here is my case:

When the user select a couple of items, I don't want to display a count message like '# of % selected' when there is just 3 items. I changed the minumimCountSelected to 10 to help me. However, when I click the 'select all' checkbox with a control with a lot of items, the "All selected" message is displayed but when the control have less than 10 items, the items are displayed instead of the "All selected" message even if all items are selected. When I invert the if like in the screenshot, it solves my problem because the evaluation of the count compared to the number of items take precedence to the other.

Thank you again for this nice jQuery plugin.

**Comment by wenzhixin** [comment]
Updated in the latest version.
