### ISSUE TITLE
Limit the number of allowed selections in checkboxes choice

### ISSUE THREAD

**Issue by sherlock85** [wenzhixin/multiple-select#125]
Is there a way to specify the maximum number of checkboxes a user can select?

For example, if a user exceeds the given limit, a message would appear announcing the allowed number of selection. In this way, the user can't select another option until he/she has removed one of the previous selections.

**Comment by wenzhixin** [comment]
Same with #194.

**Comment by vutle** [comment]
With the build in getselects we can do below to prevent more item selection.
We meed to add maxselection in into the library then we don't need to use outside variable.
And we don't really need a return.
 
var $select =  $('#select'); 
var maxselection = 4;
 onClick: function(view) {
        var count =    $select.multipleSelect('getSelects').length;
        if(count > maxselection ) {
          $select.multipleSelect('uncheck', view.value);
          return false;
        }
      }
