### ISSUE TITLE
Please make new version. Change events are not propagated to the original element on current bower version.

### ISSUE THREAD

**Issue by Duder-onomy** [wenzhixin/multiple-select#129]
The build currently on bower `1.1.0` is old and does not fire change events on the original element:

Here is a [JS Fiddle](http://jsfiddle.net/h2paxL3e/20/) to demonstrate, 
Please notice that the `jquery.multiple.select.js` file was taken from commit : c7b6065151d3c55b242523c464dac0dd5a2a8635

So, it is this snapshot (the one that is currently on bower) 
https://raw.githubusercontent.com/wenzhixin/multiple-select/c7b6065151d3c55b242523c464dac0dd5a2a8635/jquery.multiple.select.js 

In particular, it is this line that is not present in the current bower version:
https://github.com/wenzhixin/multiple-select/blob/master/jquery.multiple.select.js#L346

---

If anyone else is having this issue, you can easily change your bower.json to get the latest sha from:
```json
"multiple-select": "1.1.0"
```
To
```json
"multiple-select": "#f2402d9209b48693b3093962173ecb5495026193"
```

**Comment by jmeas** [comment]
ping @wenzhixin. This is kinda important.

**Comment by wenzhixin** [comment]
updated to 1.2.0
