### ISSUE TITLE
Possible to generate toggle list of selected options outside original list?

### ISSUE THREAD

**Issue by terned** [wenzhixin/multiple-select#132]
I'm using four drop downs for a faceted search and I want to display all the options selected from the collective lists on the form page as they are selected. I would like to tie these to the original instances so that if they are clicked the option will disappear from the page and be unchecked in the list.

Sorry if this is outside the scope of the plugin. It seems like it should be doable.

**Comment by wenzhixin** [comment]
Sorry, but I don't know what do you want.

**Comment by wenzhixin** [comment]
If you haven't solved your problem, reopen it.
