### ISSUE TITLE
Each optgroup a own ul? (Better styling)

### ISSUE THREAD

**Issue by Rodeveer** [wenzhixin/multiple-select#135]
I couldn't find a option to break the optgroup into multiple ul list.
I created a "separateUL" option in my "local version". It works just fine. Maybe an idea to add a option there into the default options aswel?

```javascript
$("select").multipleSelect({
separateUL: true,
});
```

**Comment by wenzhixin** [comment]
http://jsfiddle.net/wenyi/knbdm5hu/11/
