### ISSUE TITLE
Multiselect close by clicking on chechbox in Mozilla Firefox 32.0.3 

### ISSUE THREAD

**Issue by ghost** [wenzhixin/multiple-select#143]
When i click on checkbox (not label) multiselect closing
JS 
$('#service_activities_select').multipleSelect();

HTML
<label class="servicedCarsLbl">
    <span class="field-title"><?= _('Обслуживаемые авто')?>:</span>
    <select multiple="multiple" id="serviced_cars" name="servicedCars">

        <?foreach($view_servicedCars as $carMakes):?>
            <option value="<?= $carMakes[0]; ?>"><?= $carMakes[1]; ?></option>
        <?endforeach;?>

    </select>
</label>

**Comment by wenzhixin** [comment]
I think this bug is fixed in the latest version.
