### ISSUE TITLE
Options text gets converted to html unsafely

### ISSUE THREAD

**Issue by collinstocks** [wenzhixin/multiple-select#148]
If an option contains text with HTML special characters in it, the text is converted to HTML in the options unsafely. For example:
```html
<select id="myselect"></select>
```
```javascript
var $select = $('select#myselect');
$('<option>').attr('value', 'hello').text('<world>').appendTo($select);
$select.multipleSelect({
    single : true,
    filter : true,
    placeholder : 'Select one...'
});
```
What should happen:
* A select box should be created with one option in it, with the *text* `<world>`, just as it would appear in a real select box.

What happens:
* A select box is created with the invalid HTML tag pair `<world></world>`

Most likely, this is due to using `$(...).text()` to get the label from the HTML option element, and then treating that value as though it were HTML.

This may be the offending line: https://github.com/wenzhixin/multiple-select/blob/master/jquery.multiple.select.js#L395
By the looks of it, there may be more places where text and HTML are treated interchangeably, unsafely.

**Comment by wenzhixin** [comment]
Merged.
