### ISSUE TITLE
minimumCountSelected: 1 is not working

### ISSUE THREAD

**Issue by malhayek2014** [wenzhixin/multiple-select#149]
Hi,
First I want to thank you for this cool plugin.
I am trying to display only 1 text and if a user select more that 1 option to display the number of options selected.

so I added minimumCountSelected: 1, to the parliaments but it is not working for me.

Here is my code

$(".multipleSelectMenuMask").multiselect({
								enableFiltering: true,
								enableCaseInsensitiveFiltering: true,
								selectedClass: null,
								nonSelectedText: "Select an option",
								includeSelectAllOption: true,
								buttonWidth: "100%",
								maxHeight: 250,
								minimumCountSelected: 1
							});

I also have submitted a question on stackoverflow.com
http://stackoverflow.com/questions/26853602/how-can-i-change-the-selected-text-when-using-multiple-select-jquery-plugin

If there something I am doing wrong or this is a bug?

**Comment by wenzhixin** [comment]
release new version: v.1.2.0
