### ISSUE TITLE
Increase parent size

### ISSUE THREAD

**Issue by shikolay** [wenzhixin/multiple-select#155]
Dropdown basically increase parent size.
So if you have parent with overflow: auto 
Dropdown will cause that parent will show scroll bars on chrome
![screen shot 2014-11-18 at 6 56 32 pm 2](https://cloud.githubusercontent.com/assets/1370308/5098520/3541a6a6-6f55-11e4-839d-170e63f673e5.png)

**Comment by ltdeta** [comment]
i have the same problem... 

[dialog: multiple-select](http://www.bilder-space.de/bild-multipleselectoverflowjpg-21120.htm)

**Comment by ntucakovic** [comment]
Even though container option is useful, sometimes it doesn't give the right outcome. If offset is placed there should be scroll and resize events attached, to reposition the ms-drop accordingly. Hell breaks loose if you are having quite complex layout, with multiple fixed, collapsible elements etc... Kinda bummer this problem wasn't anticipated.

Hopefully I'll make my first contribution to github soon and fix this one as it's the best multi/single select jquery plugin by far.

**Comment by wenzhixin** [comment]
Use `container` to solve this problem.
