### ISSUE TITLE
optgroup label is not automatically selected in multiselect when all the option of that optgroup is seleceted using <setSelects>. 

### ISSUE THREAD

**Issue by prem2014** [wenzhixin/multiple-select#156]
During edit of a form when options of a optgroup is set to selected using $("select").multipleSelect("setSelects", ids); // where ids is array of values of options and when ids contains values of all the options of particular <optgroup> then the check box which is genereated for optgroup(when checked with mouse it checks all the options of optgroup and vice-versa) is not checked when all the options of a optgroup is seleceted using setSelects. 

Please look in to issue as soon as possible, or comment If I am missing something in your plugin. 

Thanks for providing great multipleselect plugin.

**Comment by chitrank-samaiya** [comment]
Yes, This is valid value, I am also facing same issue. While editing, optgroup is not checked when all the childrens are checked.

**Comment by wenzhixin** [comment]
Fixed this in the latest version: http://jsfiddle.net/wenyi/knbdm5hu/7/
ref #227, #255
