### ISSUE TITLE
dropdown in thead shows behind tbody ?

### ISSUE THREAD

**Issue by stevears** [wenzhixin/multiple-select#157]
Hi.  
Newbie here!

I'm trying to include a dropdown list (multiple select) in a fixed table header (using jquery.floatThead) but the list is actually showing behind the table body? I tried to play with z-index with no success.

See : http://jsfiddle.net/vh4j7ozg/11/

Anything that I am missing ?

Thanks

**Comment by wenzhixin** [comment]
ref #255
