### ISSUE TITLE
When the option text is too long it seems to be going outside the menu.

### ISSUE THREAD

**Issue by malhayek2014** [wenzhixin/multiple-select#158]
Hi,
I am seeing an issue. when the option in the menu is too long, then the text shows up outside the menu.

Here is my code
							$(".multipleSelectMenuMask").multiselect({
								enableFiltering: true,
								enableCaseInsensitiveFiltering: true,
								selectedClass: null,
								nonSelectedText: "Select an option",
								includeSelectAllOption: true,
								buttonWidth: 250,
								maxHeight: 250,
								width: 250,
								minimumCountSelected: 1
							});

**Comment by wenzhixin** [comment]
#239 Show item ellipsis and tooltip: http://jsfiddle.net/wenyi/knbdm5hu/5/ maybe help.
ref #255

**Comment by salamsoliman** [comment]
Cab
