### ISSUE TITLE
Wide dropdown causes more than one option on a line

### ISSUE THREAD

**Issue by clairestreb** [wenzhixin/multiple-select#159]
I have a single-select dropdown that I had to expand to 660px to accommodate long text values, and now my options are appearing on the same line.  Option 2 is overwriting on top of option 1's text.  I set multipleWidth to 660px, and it made no difference.  I had to fight hard at work to justify using this plugin, and now it isn't working.  :(  Please help!

**Comment by wenzhixin** [comment]
You can use `.ms-parent label` to defined your css.
