### ISSUE TITLE
Change MultiSelect to Single Select on a Condition

### ISSUE THREAD

**Issue by cimbomluufuk** [wenzhixin/multiple-select#161]
Hi All,

I think it will be great, if we have a condition to change the .multipleSelect to single selection. E.g. On a condition the multipleSelection to change between multiple to single or single to multiple.

**Comment by ree48012** [comment]
Is that possible

**Comment by goraya78** [comment]
is that possible ?
 i need to convert multi select to single select on if ajax return 1 .. 
can you share example...

**Comment by wenzhixin** [comment]
Use the `destroy` method.
Example: http://multiple-select-live.wenzhixin.net.cn/code/wenzhixin/490
