### ISSUE TITLE
.bower.json missing "main" property

### ISSUE THREAD

**Issue by mikeinsf** [wenzhixin/multiple-select#162]
Modified file as such...
{
 "name": "multiple-select",
 "main": "jquery.multiple.select.js",
 "homepage": "https://github.com/wenzhixin/multiple-select",
 "version": "1.1.0",
 ...

**Comment by stereokai** [comment]
:+1: Thanks for the update.

**Comment by wenzhixin** [comment]
added: https://github.com/wenzhixin/multiple-select/blob/master/bower.json
