### ISSUE TITLE
Unexpected behavior when using select all/none and type-ahead filter

### ISSUE THREAD

**Issue by esadun** [wenzhixin/multiple-select#164]
When using the filter option (for instance the "Filter1" demo), I find it unexpected that the "[Select all]" checkbox operates only on those items currently shown. On "Filter1" demo if a user :

1) Selects all by checking "[Select all]"
2) Begins to filter the items by typing "ab" in the "Filter1" demo
3) Unchecks "[Select all]"

The user will find that the control reports "30 of 31 selected," and opening the multi-select again will reveal that all but "abc" are checked, meaning that Step 3 above only operated on the items being shown (just "abc"). Instead of this behavior I personally would expect that Step 3 would truly deselect everything whether or not a filter is active, leaving an empty control.

**Comment by wenzhixin** [comment]
Hi @esadun, I don't think you said is more reasonable. Because when you do filter, the all items is the filter results, so we [select all], it just select the all filter results.
