### ISSUE TITLE
Crash on Chrome after selecting one of the choices or using select all

### ISSUE THREAD

**Issue by jlavos** [wenzhixin/multiple-select#165]
It crashs in chrome (39.0.2171.95 m) all the time when clickng one of the checkboxes or on onw of the options, including select all.

Tried in ie 11, safari (5.34.57.2) and firefox 35.0 and it works fine.

The options for the object are: 

 $('#myselect').multipleSelect({
        filter: true,
        placeholder: "Select resources",
        minimumCountSelected: 1       
    });

**Comment by wenzhixin** [comment]
Test in chrome(45.0.2454.101), the problem does not exist: http://jsfiddle.net/wenyi/knbdm5hu/10/
