### ISSUE TITLE
i wanna add placeholder option in filter input

### ISSUE THREAD

**Issue by zeroty** [wenzhixin/multiple-select#166]
//add init: function >>  if (this.options.filter) { >>
html.push( aaa + this.options.filterPlaceholder + bbb);

//add $.fn.multipleSelect.defaults = { >>
filterPlaceholder: ''

**Comment by wenzhixin** [comment]
any pull request is welcome

**Comment by mcvova** [comment]
Hi, does it implemented?

**Comment by wenzhixin** [comment]
http://multiple-select.wenzhixin.net.cn/examples/#filter-placeholder.html
