### ISSUE TITLE
maxHeight

### ISSUE THREAD

**Issue by vinceweeks** [wenzhixin/multiple-select#167]
Hello, trying to set the maxHeight property like so:

<strong>Dealers</strong>
	<div class="form-group">
	@Html.ListBoxFor(mi => mi.AccountFilter.selected_dealers, new SelectList(Model.AccountFilter.dealers, "ID", "Text1"), new { @class = "id-dealers", @multiple = "multiple", @height = "100px" })
	</div>

$('.id-dealers').multipleSelect({
	width: '100%',
	maxHeight: '50',
	placeholder: "Select a Dealer"
});

Doesn't have any effect, Any ideas? Thanks

**Comment by wenzhixin** [comment]
A working example: http://jsfiddle.net/wenyi/knbdm5hu/14/
ref #255
