### ISSUE TITLE
option - container: improvement

### ISSUE THREAD

**Issue by ltdeta** [wenzhixin/multiple-select#172]
- option `container` is not in the  [documentation](http://wenzhixin.net.cn/p/multiple-select/docs/#documentation)
- setting `option-container` and `option-width` is not set (undefined) the  `dropdown list` width does not show the same as the select input field.

the follwing new line changes this

[jquery.multiple.select.js](https://github.com/wenzhixin/multiple-select/blob/master/jquery.multiple.select.js)

``` js
....
   if (this.options.container) {
                var offset = this.$drop.offset();
                this.$drop.appendTo($(this.options.container));
                this.$drop.offset({ top: offset.top, left: offset.left });

                // **** new ****
                this.$drop.outerWidth(this.$parent.outerWidth())
            }
...
```

![container](https://cloud.githubusercontent.com/assets/1563652/6149784/84b944e8-b20b-11e4-999a-7a157665461c.jpg)

**Comment by ltdeta** [comment]
moving a dialog with open dropdown list ,  the dropdown list holds its position

![dropdown-position](https://cloud.githubusercontent.com/assets/1563652/6188665/e4cb5360-b393-11e4-9c09-e3a68f1d2293.jpg)

**Comment by DavidePastore** [comment]
:+1:
