### ISSUE TITLE
dropdown list arrow - wrong position

### ISSUE THREAD

**Issue by ltdeta** [wenzhixin/multiple-select#174]
here you can see the offset
![multiple-select-wrong-arrow-down-position](https://cloud.githubusercontent.com/assets/1563652/6169596/f000c60e-b2ce-11e4-973a-c7d92e2ad647.png)

fixed: [file with the correct position](http://www.file-upload.net/download-10290802/multiple-select-fix.png.html
)

**Comment by wenzhixin** [comment]
Merged, thanks a lot!
