### ISSUE TITLE
SetSelect does not set Group

### ISSUE THREAD

**Issue by fkfouri** [wenzhixin/multiple-select#188]
Dear

I added in your script the followin code at line 419.

            $.each(that.$selectGroups, function (i, val) {
                var group = $(val).parent().attr('data-group'),
                    $children = that.$selectItems.filter('[data-group="' + group + '"]');
                $(val).prop('checked', $children.length &&
                    $children.length === $children.filter(':checked').length);
            });	

When I set by code all children of a group, the parent group was not set automatically. After include this code the multiple-select works.

Could you please consider this code in next version?

**Comment by StonyMayhall** [comment]
I also added this code to the refresh method. Refresh was not setting optgroups to checked correctly after dynamically adding optgroups and options.

**Comment by wenzhixin** [comment]
Merged.
