### ISSUE TITLE
Cannot auto-hide when mouse focus out the control

### ISSUE THREAD

**Issue by nicoshao** [wenzhixin/multiple-select#190]
The dropdown not always hidden after selection and click other place of the page. Please see below.

http://jsfiddle.net/Nico_Shao/t5ngnxsk/4/

**Comment by AlexisDarbon** [comment]
AndresBott pulled a requested concerning this problem. 
https://github.com/wenzhixin/multiple-select/pull/186

I changed my own js file according to his code and the problem disappeared.

**Comment by sxlifeng** [comment]
I also meet this problem.How to solve?I find this code about this function on the 40th line in jquery.multiple.select.js, and i think delete first condition maybe is true.

**Comment by danodm** [comment]
I was having this same issue, and fixed it by copying the JS on the demo site, into my own build.

eg: Copy his JS from this url - http://wenzhixin.net.cn/p/multiple-select/jquery.multiple.select.js - into your own downloaded JS file.

**Comment by Rydeck** [comment]
i replaced my downloaded js with the code you just provided but I notice no difference.
The selectbox keeps open when I click elsewhere.
Another suggestion to solve this?

**Comment by rahulsen002** [comment]
It seems the problem is not yet resolved. I am facing the same issue. Kindly help out.

**Comment by wenzhixin** [comment]
Fixed this in the latest version.
