### ISSUE TITLE
focus and blur not working

### ISSUE THREAD

**Issue by jframier** [wenzhixin/multiple-select#191]
Tried the focus and blur in http://wenzhixin.net.cn/p/multiple-select/docs/
and it is not working
I am trying to close a selection when focus is lost or when another is on focus. Multiple selection on the screen.
Unlike your site, the documentation downloaded  does not close the previous open selection
Is there a fix I'm missing ?
Is there any intention of fixing the focus and blur ?
Thanks in advance

**Comment by danodm** [comment]
I was having this same issue and fixed it by copying the JS on the demo site into my own build.

i.e copy his JS from this url - http://wenzhixin.net.cn/p/multiple-select/jquery.multiple.select.js - into your own downloaded JS file.

I haven't investigated the differences (lack of available time), though the above worked for me.

**Comment by JasonHanley** [comment]
Same problem here.

I believe this commit https://github.com/wenzhixin/multiple-select/commit/f00d5d6097fa66db3f185bed014e439345a97be1 screwed up de-focusing.

Using the older version works as expected.

**Comment by wenzhixin** [comment]
Focus and blur example: http://jsfiddle.net/wenyi/knbdm5hu/21/
ref #255
