### ISSUE TITLE
Is it possible to not submit the 'selectItem*' values?

### ISSUE THREAD

**Issue by janhartmann** [wenzhixin/multiple-select#192]
I have a select, which is converted to a multiple-select using this plug-in.

The problem is when I submit (GET) the form, the query-string is polluted with the values of the selectItems.

E.g. `&Query.Departures=MySelectedValue&selectItemQuery.Departures=MySelectedValue`

This is redundant, and I would like to only have my `&Query.Departures=MySelectedValue` which is the selected value. Any way to solve this? :-)

**Comment by quordev** [comment]
If you look at jquery.multiple.select.js, you can find following code.

this.selectAllName = 'name="selectAll' + name + '"';
this.selectGroupName = 'name="selectGroup' + name + '"';
this.selectItemName = 'name="selectItem' + name + '"';

Replace 'name' with 'class'.

That will solve the issue.

**Comment by wenzhixin** [comment]
Fixed this bug.
