### ISSUE TITLE
Set maximum selected options

### ISSUE THREAD

**Issue by myadlan** [wenzhixin/multiple-select#194]
Hi. 
I'd like to ask if we can set maximum selected options. 

I want to limit my users to choose their top 5 options only out of 22 options.

I also want the count to show 3 of 5 selected. When all has been chosen, it shows 5 of 5 selected.

Thank you.

**Comment by DuneGestion** [comment]
Same need here, a max selectable option. I'll try to make one myself if it doesn't exist yet, shouldn't be too hard, but i wanted to know if someone already didn't make this. Thanks again for your work, it helped us a lot

**Comment by wenzhixin** [comment]
Any pull request is welcome~!

**Comment by sharathdaniel** [comment]
It would be great if this feature in inbuilt in the plugin itself.

**Comment by ghiscoding** [comment]
I think this issue can be closed since PR #610 added the `onBeforeClick` that could be used to address the use case provided above

**Comment by wenzhixin** [comment]
@ghiscoding, OK, thanks for your feedback.
