### ISSUE TITLE
Filter Holding Text

### ISSUE THREAD

**Issue by softwaretech** [wenzhixin/multiple-select#199]
When a user searches via filter, the text is held in the text box after an item is checked.  

Two suggestions:  After a box is checked, clear the input text box or when the focus is off the dropdown, then clear the filter text box.

**Comment by wenzhixin** [comment]
> After a box is checked, clear the input text box
This is not reasonable.

> when the focus is off the dropdown, then clear the filter text box.
The latest version supports this feature.

So, close this issue.
