### ISSUE TITLE
minimumCountSelected doesn't work due to typo

### ISSUE THREAD

**Issue by dazzknowles** [wenzhixin/multiple-select#211]
Hi,

For anyone trying to use the minimumCountSelected option, there is a typo in the 1.1 source and the option is spelled minumimCountSelected. You therefore either have to use this name or, like I did, fix the two entries in the source where this occurs.

**Comment by dazzknowles** [comment]
Sorry, just realised that this is a duplicate of #149

**Comment by wenzhixin** [comment]
release new version: v.1.2.0
