### ISSUE TITLE
every select on page gets multiple class

### ISSUE THREAD

**Issue by servant38** [wenzhixin/multiple-select#212]
Everything works when using this plugin except that every select on my page gets the multiple select class, even the ones that haven't the multiple="multiple" property in their select.

I put next lines under the select that has to be multiple:
<script src="js/jquery.multiple.select.js"></script>
    			<script>
        			$("select").multipleSelect({
            			filter: true
        			});
    			</script>

Do I have to change something?

**Comment by servant38** [comment]
Ok solved it by adding a class to the select and using the specific class in the script like this:

<script>
        			$("select.multi").multipleSelect({
            			filter: true
        			});
    			</script>

**Comment by wenzhixin** [comment]
Great, close this issue.
