### ISSUE TITLE
Filter Dynamic Text

### ISSUE THREAD

**Issue by softwaretech** [wenzhixin/multiple-select#214]
When I have text appearing dynamically via ajax and I go to filter, the filter will remove all other options but not bring my option toward the top.

Example:

Supposed I have a list of 31 ice cream flavors.  At the top is chocolate and the 31st flavor at the bottom is Watermelon.  If I search for watermelon, all of my other options disappear but each `<li>` stays in place and my watermelon option is still 31st in line instead of moving to the top.

I hope that's clear.

Really appreciate all of the work you're doing!!

**Comment by wenzhixin** [comment]
Can you provide a jsFiddle base on #255?

**Comment by wenzhixin** [comment]
Please update to the latest version, if the problem exists reopen it and provide a jsfiddle, thanks.
