### ISSUE TITLE
multipleSelect('refresh'); won't refresh single multipleSelects

### ISSUE THREAD

**Issue by JeanneD4RK** [wenzhixin/multiple-select#215]
I'm using multipleSelect('refresh'); to refresh selects that are modified by jQuery with $("window").ready.
This method works fine with multipleSelects that have single option disabled, but not with the one that have single option enabled. The select stays on default value or placeholder.

**Comment by kaktus40** [comment]
I had the same issue. After using name parameter, the refreshed action worked!
https://github.com/wenzhixin/multiple-select/issues/231
