### ISSUE TITLE
Lists updated with duplicate "Select All" and "No Matches Found" items on refresh

### ISSUE THREAD

**Issue by lehket** [wenzhixin/multiple-select#226]
When using refresh, I'm getting multiple "Select All" checkboxes in the resulting list.  Upon investigating, I found that the refresh builds and appends a new ul structure each time it's called, and each ul is given its own "Select All" and "No Matches Found" items.  I've fixed this in my local copy with the following code, although it may not be the best way to approach it, starting at line 72 in jquery.multiple.select.js:

            var ul = $('<ul></ul>');
            
            // Fix for refresh issue
            var refresh = this.$drop.find('ul').length > 0;
            
            // Fix for refresh issue
            //if (this.options.selectAll && !this.options.single) {
            if (this.options.selectAll && !this.options.single && !refresh) {
                ul.append(
                    '<li class="ms-select-all">' +
                    '<label>' +
                    '<input type="checkbox" ' + this.selectAllName + ' /> ' +
                    this.options.selectAllDelimiter[0] + this.options.selectAllText + this.options.selectAllDelimiter[1] +
                    '</label>' +
                    '</li>'
                );
            }
            $.each(this.$el.children(), function (i, elm) {
                ul.append(that.optionToHtml(i, elm));
            });
            
            // Fix for refresh issue
            //ul.append('<li class="ms-no-results">' + this.options.noMatchesFound + '</li>');
            if (!refresh) {
                ul.append('<li class="ms-no-results">' + this.options.noMatchesFound + '</li>');
            }
            
            // Fix for refresh issue
            //this.$drop.append(ul);
            if (refresh) {
                this.$drop.find('ul').append(ul.children());
            } else {
                this.$drop.append(ul);
            }

**Comment by wenzhixin** [comment]
Fixed this bug in the latest version.
