### ISSUE TITLE
firefox click bug

### ISSUE THREAD

**Issue by m-jazayeri** [wenzhixin/multiple-select#230]
Hey, it seems you fixed the "firefox click bug" in Version 1.0.9. I'm currently using version 1.1.0, but the bug still exists. Any comment or advice is appreciated.

**Comment by wenzhixin** [comment]
Can you provide a jsFiddle base these example: https://github.com/wenzhixin/multiple-select/issues/255?

**Comment by wenzhixin** [comment]
Please update to the latest version, if the problem exists reopen it and provide a jsfiddle thanks.
