### ISSUE TITLE
two selector with single property set ture not working

### ISSUE THREAD

**Issue by 2089717323** [wenzhixin/multiple-select#231]
I met a problem when use this multiple select js with single option. I set tow selector with sigle option.  when aa chose/click a option, the selected option in other selector bb will be clear. seems that a clink action would impact another selector option. does anyone experienced same problem?
  $("#aa select").multipleSelect({single: true});
  $("#bb select").multipleSelect({single: true});

**Comment by avinash-bhatia** [comment]
Maybe this one could be of help : https://github.com/wenzhixin/multiple-select/issues/118

**Comment by kaktus40** [comment]
you should use name parameter:
```javascript
$("#aa select").multipleSelect({single: true,name:'first'});
$("#bb select").multipleSelect({single: true,name:'second'});
```

**Comment by wenzhixin** [comment]
Support this feature in the latest version: http://jsfiddle.net/wenyi/knbdm5hu/6/
