### ISSUE TITLE
question: update for all issues(fixed) and pull requests

### ISSUE THREAD

**Issue by ltdeta** [wenzhixin/multiple-select#234]
wenzhixin using most of his time for bootstrap
but a lot of progress has been made here in recent times (fixed issues and pull requests)

who can merge all these improvments into a new version ?

**Comment by wenzhixin** [comment]
Update to v1.2.0: https://github.com/wenzhixin/multiple-select/blob/master/CHANGELOG.md#120

**Comment by ltdeta** [comment]
push
is there are a fork with more enhancements (last release 1.2.1)?
