### ISSUE TITLE
Cant make filter working

### ISSUE THREAD

**Issue by urtziu** [wenzhixin/multiple-select#238]
Hi all, 
Very useful and well done multiple select you have here! 
I got the multiple selector working but when I try to implement the filter it doesn’t work. 
Here you have a fiddle with the example (I put all of the js code to make it work, don’t know how to do it without putting the full code on the fiddle): http://jsfiddle.net/2mSUS/679/ 

Thanks for all,
Urtzi.

**Comment by wenzhixin** [comment]
A working example: http://jsfiddle.net/wenyi/2mSUS/716/, please update to the latest version.
