### ISSUE TITLE
OnBlur not working

### ISSUE THREAD

**Issue by jabreuar** [wenzhixin/multiple-select#244]
Why onblur and onfocus are fired together?

$('#teste').find('select').multipleSelect({
            onOpen: function() {
                alert('Select opened!');
            },
            onClose: function() {
                alert('Select closed!');
            },
            onCheckAll: function() {
                alert('Check all clicked!');
            },
            onUncheckAll: function() {
                alert('Uncheck all clicked!');
            },
            onFocus: function() {
                alert('focus!');
            },
            onBlur: function() {
                alert('blur!');
            }
        });

**Comment by wenzhixin** [comment]
Because you use `alert`, so when you on focus it always on blur.

**Comment by wenzhixin** [comment]
I think this is not a bug.
