### ISSUE TITLE
undesired outline of the hidden select field with twitter bootstrap and chrome

### ISSUE THREAD

**Issue by jm-style** [wenzhixin/multiple-select#247]
onfocus first click:
![bug1](https://cloud.githubusercontent.com/assets/5020902/10098285/80536588-6380-11e5-84b3-1722b55781d5.png)

click again:
![bug2](https://cloud.githubusercontent.com/assets/5020902/10098287/8348ddf4-6380-11e5-954f-d1269df2294d.png)

I've tried modify css as below but nothing works...

select [multiple]:focus, select [multiple]{
	border:0!important; 
	outline: 0!important; 
	-webkit-box-shadow: none!important;
	box-shadow: none!important;
}

**Comment by wenzhixin** [comment]
http://jsfiddle.net/wenyi/knbdm5hu/2/

**Comment by jm-style** [comment]
Yes but this solution completely loses the twitter bootstap's border effect on focus...
Finally it was only specify a padding = 0 on .ms-parent element: http://jsfiddle.net/knbdm5hu/9/

**Comment by wenzhixin** [comment]
:+1:
