### ISSUE TITLE
problem undefined

### ISSUE THREAD

**Issue by rcayadi** [wenzhixin/multiple-select#248]
Trying using the basics 1 got this this.$el.attr(...) is undefined , error at line 183

**Comment by samface** [comment]
Same for me. 

Uncaught TypeError: Cannot read property 'split' of undefined
MultipleSelect.events @ jquery.multiple.select.js?ver=4.3.1:183
MultipleSelect.init @ jquery.multiple.select.js?ver=4.3.1:98
(anonymous function) @ jquery.multiple.select.js?ver=4.3.1:529
m.extend.each @ jquery.js?ver=1.11.3:2
m.fn.m.each @ jquery.js?ver=1.11.3:2
$.fn.multipleSelect @ jquery.multiple.select.js?ver=4.3.1:512
(anonymous function) @ (index):695

Using chrome.

**Comment by samface** [comment]
Apparently the select-tag is required to have an id attribute and the multiple-select script will not work without one, yet no such thing is mentioned in the documents nor can it be told from any of the code examples. Please update the documentation. Or maybe, as a suggestion, alter the code to use the name attribute as fallback if no id-attribute is present.

**Comment by wenzhixin** [comment]
Fixed this bug.
