### ISSUE TITLE
On Hover

### ISSUE THREAD

**Issue by derekang** [wenzhixin/multiple-select#249]
Currently, we have to click on the selectbox to open it. how do we tweak it such that when we hover over the selectbox, it will open?

**Comment by wenzhixin** [comment]
In current version, do not support this feature, any pull request is welcome.

**Comment by wenzhixin** [comment]
Thanks for @djhvscf , added this option now.

**Comment by alinache88** [comment]
Thanks for the plugin. Really appreciate it. But if you added onHoverOpen you should add onHoverClose..

Something like this.

`            if (this.options.openOnHover) {
                $(".ms-parent").mouseover(function (e) {
                    that.open();
				 });
            }
            if (this.options.closeOnHover) {
                $(".ms-parent").mouseout(function (e) {
			         that.close();
                });
            }	`

**Comment by alinache88** [comment]
because as it is now, you are "showing" it on both the mouseover and the mouseout event...Which does not seem very practical.
