### ISSUE TITLE
Broken style inside a table

### ISSUE THREAD

**Issue by lyhongpon** [wenzhixin/multiple-select#250]
The list of options is hidden behind td tag. I've tried adding position: relative to td but still it doesn't work. It's probably CSS causing this.

**Comment by lyhongpon** [comment]
The list of options is hidden behind td tag. I've tried adding position: relative to td but still it doesn't work. It's probably CSS causing this.

**Comment by wenzhixin** [comment]
Use `container` option to solve this problem.
