### ISSUE TITLE
refresh method duplicates the options

### ISSUE THREAD

**Issue by abdfahim** [wenzhixin/multiple-select#251]
.multipleSelect("refresh") method duplicates the options tree ....

http://jsfiddle.net/abdfahim/2mSUS/707/

**Comment by PlippiePlop** [comment]
I concur same here, I am using it in a cascade plugin where the callback refreshes the list. Spend two hours on the why the list get doubled. Refresh needs to clear the list and refill it from the select.

**Comment by wenzhixin** [comment]
Fixed this bug in the latest version.
