### ISSUE TITLE
Is it possible Disable option should not added in total options 

### ISSUE THREAD

**Issue by iamsalmanafzal** [wenzhixin/multiple-select#252]
if i have 12 option and in 12 i have 2 disabled options, so it should show.

6 selected of 10

**Comment by wenzhixin** [comment]
In current version, do not support this feature, any pull request is welcome.

**Comment by alexisgayte** [comment]
Hi ,

My fork fixed this issue.

Alexis

**Comment by wenzhixin** [comment]
Fixed in the develop branch: http://multiple-select-live.wenzhixin.net.cn/code/wenzhixin/948
