### ISSUE TITLE
jsFiddle examples

### ISSUE THREAD

**Issue by wenzhixin** [wenzhixin/multiple-select#255]
- Basic example: http://jsfiddle.net/wenyi/knbdm5hu/1/
- Optgroups example: http://jsfiddle.net/wenyi/knbdm5hu/12/
- Filter example: http://jsfiddle.net/wenyi/knbdm5hu/13/
- Focus and blur example: http://jsfiddle.net/wenyi/knbdm5hu/21/
- #247 Remove outline style: http://jsfiddle.net/wenyi/knbdm5hu/2/
- #239 Show item ellipsis and tooltip: http://jsfiddle.net/wenyi/knbdm5hu/5/
- #181 Custom optgroup style: http://jsfiddle.net/wenyi/knbdm5hu/11/
- #157 Set `container` to solve position problem: http://jsfiddle.net/vh4j7ozg/14/
- #102 Width automatically extended: http://jsfiddle.net/knbdm5hu/55/
- #264 Use `textTemplate` option: http://jsfiddle.net/knbdm5hu/53/
- #387 Change selected background color: http://jsfiddle.net/wenyi/knbdm5hu/2341/

**Comment by mugdha1b** [comment]
Very slow when the list is having 10,000 items.
Its is taking too much time (6-9 seconds) to list the items in the drop-down.
Please suggest

**Comment by Jojikt** [comment]
How Can I sort selected checkbox!

Please Guide me

**Comment by bliky** [comment]
有下拉树选择功能吗

**Comment by Life-is-short** [comment]
How it is possible to force selectbox to reset to defaults which were picked from default selector?

**Comment by antishok** [comment]
Made an RTL example (this one is in hebrew):  http://jsfiddle.net/jkcam5pq/

**Comment by rakhiattal** [comment]
Please give an example of dependent Selectbox using this library

**Comment by desphub** [comment]
not enough EM

**Comment by abualk** [comment]
I really love this plugin, I tried using it on bs4 but the shows outline inside the button of class ms-choice. I hope you fix the compatibility with bs4

**Comment by wenzhixin** [comment]
@abualk Thanks for your feedback.

**Comment by averbner** [comment]
Is there a way that by default the value is all selected?

**Comment by wenzhixin** [comment]
@averbner 
```
<select>
  <option selected>...</option>
</select>
```

**Comment by paolobiavati** [comment]
All jsfiddle examples miss the library js and css


<link rel="stylesheet" href="https://unpkg.com/multiple-select@1.5.2/dist/multiple-select.min.css">


<script src="https://unpkg.com/multiple-select@1.5.2/dist/multiple-select.min.js"></script>
