### ISSUE TITLE
Conflict with Datatable

### ISSUE THREAD

**Issue by wangcansun** [wenzhixin/multiple-select#260]
when I create a data table with dataTable.js dynamically the multiple-select that worked before will not work .I think the function in dataTable called dataTable() will make a difference to the multi-select.And how can I do for it?

**Comment by wenzhixin** [comment]
You can use [bootstrap-table](https://github.com/wenzhixin/bootstrap-table) and multiple-select, here is an working example: http://jsfiddle.net/wenyi/e3nk137y/3816/

**Comment by wenzhixin** [comment]
ref #255
