### ISSUE TITLE
REQ: Add more Keyboard navigation options

### ISSUE THREAD

**Issue by PlippiePlop** [wenzhixin/multiple-select#261]
Please add  more keyboard navigation options.

**For example**
- Tab key = move into and out of select
- Arrow key Up/Down = move up or down to navigate options in list 
- Enter key = highlight (select) or to un-highlight (deselect) options
- Space = jump to (first) selected item in list (if long list scrolling)

**Comment by ankitsawar** [comment]
Is this feature works now. can anyone help with this?

It will be great if this feature works.

**Comment by israhes** [comment]
> Is this feature works now. can anyone help with this?

No it isn't .

> It will be great if this feature works.

I had to use chosen js just for this feature.

**Comment by wenzhixin** [comment]
Ref #613, it works in the latest version(1.7.0).
