### ISSUE TITLE
With multiple select with optgroup, can we get the selected text as a JSON? 

### ISSUE THREAD

**Issue by vnatarajan-rpx** [wenzhixin/multiple-select#271]
With Optgroups1,

I am getting the result as 

```
"[Group 1: Option 1, Option 3]", "[Group 2: Option 5]", "[Group 3]"
```

Can it get as a JSON string?

**Comment by wenzhixin** [comment]
`getSelects` return an array:
http://multiple-select.wenzhixin.net.cn/examples/#setSelects-getSelects.html
