### ISSUE TITLE
can the plugin preserve the tabindex of the original select?

### ISSUE THREAD

**Issue by yairpe** [wenzhixin/multiple-select#276]
Right now the tabindex is lost and when the user uses Tab key to move from field to field in a form, multiple-select field breaks the sequence.

The original `<select>` has a tabindex, but the `<button>` that replaces it does not.

**Comment by mahj091** [comment]
Any updates? Any workarounds?

**Comment by echo-five** [comment]
Any updates? Any workarounds?
