### ISSUE TITLE
change fired two times

### ISSUE THREAD

**Issue by osgosa** [wenzhixin/multiple-select#277]
When In the multiple select I select one option the change event is fired two times. I can not find a solution. I ca not put onChange option in select tag.

```
$( document ).ready(function(){
    $('body').off('change' , '#id_customer').on('change' , '#id_customer', function(e){
        e.stopImmediatePropagation();
        charge_select_option_customer();
    });
});
```

Best Regards and sorry for my bad english.

**Comment by djhvscf** [comment]
Can you provide an example?

**Comment by dodas** [comment]
This bug was introduced in cfdab0e9eec70592a5c1a33760b7f87211325094 , on line 370 there was added `trigger('change')` which is then fired again on line 380.

**Comment by moonflash** [comment]
+1

**Comment by trafficinc** [comment]
On line 510: Add this.
            if (!isInit **&& isInit !== undefined**) {
                this.$el.trigger('change');
            }
Let me know if it works out for you.

**Comment by Rosscotini** [comment]
I can confirm @trafficinc solution works! thanx

**Comment by Videles** [comment]
> On line 510: Add this.
> if (!isInit **&& isInit !== undefined**) {
> this.$el.trigger('change');
> }
> Let me know if it works out for you.

Didnt work for me in version 1.2.1 but it showed me exactly where to search, I personally solved it like this.

// this.$el.val(this.getSelects()).trigger('change');
this.$el.val(this.getSelects()).trigger('click');

**Comment by wenzhixin** [comment]
Fixed in the latest version.
