### ISSUE TITLE
Dynamic Multipleselect Issue

### ISSUE THREAD

**Issue by soumya2080** [wenzhixin/multiple-select#278]
I have added a `<select id="someId">`  tag dynamically to the html  and populated the `<option /> ` and applied the $("#someId").multipleSelect() . It is showing error in console **Uncaught TypeError: $(...).multipleSelect is not a function** .

The Code can be visualize as:

` $(#button).on("click", function() {
       $("#someDiv").append("<select id='someId' multiple='multiple'><option value='someValue'>someValue</option>");
        $("#someId").multipleSelect();
}); `

**Comment by djhvscf** [comment]
@soumya2080 did you fix this?

**Comment by soumya2080** [comment]
No, actually the description which I had provided is little wrong. I was
using jquery modal to generate pop-up. Inside that pop-up I had a multiple
select option. I'm unable apply .multipleSelect() in that case.

**Comment by jmanzo** [comment]
Hi @soumya2080 could you fix this? I having a bug similar to this ticket
