### ISSUE TITLE
Optgroups as columns

### ISSUE THREAD

**Issue by smartcorestudio** [wenzhixin/multiple-select#28]
It's not an issue. I think this can be a good idea to have a possibilility to display each optgroup in a separate column
for example we can turn this:
![2013-11-21 10_26_21-multiple select](https://f.cloud.github.com/assets/2891792/1589642/f1df65c0-5276-11e3-8d3c-27f148aac289.png)
into this:
`
Group1   Group2   Group3
Opt-11     Opt-21     Opt-31
Opt-12     Opt-22     Opt-32
Opt-13     Opt-23
`
I think, it can add additional flexibility and in some cases it will be easier to read

**Comment by wenzhixin** [comment]
Wontfix this feature.
