### ISSUE TITLE
Issue in ASP.NET

### ISSUE THREAD

**Issue by MarkoEitel** [wenzhixin/multiple-select#281]
Hello,
I'm working with ASP.NET Webforms.

If I use a Listbox with Modelbinding and Autopostback=true then the page loops reloading.
Can you help?

Greetings from Berlin,Germany
Marko

**Comment by wenzhixin** [comment]
Sorry, I am not familiar with ASP.NET so don't know how to help.

**Comment by djhvscf** [comment]
@MarkoEitel let me get a try with this context

**Comment by DanPFW** [comment]
I had a similar issue.  I had to make sure my jquery was being loaded in the head of the page.you can't load it with the scriptmanager in a master page.

**Comment by wenzhixin** [comment]
Close this issue because it's a little old if you also need to help please reopen it.
