### ISSUE TITLE
single select dropdown with clear selection option?

### ISSUE THREAD

**Issue by DanPFW** [wenzhixin/multiple-select#282]
I'm currently using this class to display multiple checkboxes under groups with the additional select all and search (With Optgroups example).  I'd also like to use this class as a single select control (radio buttons) within OptGroups, with an option to clear any selections.  So, basically a radio button in place of the "select all" checkbox to clear the presently selected radio button in the drop down.  Is this possible by setting existing properties, or does this functionality need to be added?

**Comment by wenzhixin** [comment]
Fixed in #500
