### ISSUE TITLE
Disable/Enable drops filter option

### ISSUE THREAD

**Issue by MonizDave** [wenzhixin/multiple-select#283]
When I initialize with filter: true it's there. But I have a toggle for disable/enable and when that's used the filter is gone.

I tried manually forcing it to come back with no luck

**Comment by wenzhixin** [comment]
Can you provide a jsfiddle? #255

**Comment by MonizDave** [comment]
I was using it with angular and the select>options were generated with ng-repeat and it was misbehaving, but I added a custom directive to fire when the repeat was done and now it works great! 

You can close this.

**Comment by wenzhixin** [comment]
Great!

**Comment by lvandeuren** [comment]
Could you share the directive you added? The bug is still there

**Comment by MonizDave** [comment]
You need to include this with the data-ng-repeat: on-finish-render="ngRepeatFinished"

The directive is as follows (obviously replace Module with your Module Object):  

Module.directive('onFinishRender', function ($timeout) {
	return {
		restrict: 'A',
		link: function (scope, element, attr) {
			if (scope.$last === true) {
				$timeout(function () {
					scope.$emit('ngRepeatFinished');
				});
			}
		}
	}
});

**Comment by lvandeuren** [comment]
Awesome! Actually my problem was caused by running "refresh" before initializing the multipleSelect, which supplied default options... by default
