### ISSUE TITLE
Widget is different size in different browsers

### ISSUE THREAD

**Issue by JayAshday** [wenzhixin/multiple-select#287]
Using version 1.2.0 (I know a newer one's been released, but the CDN doesn't have that and the changelog doesn't indicate a fix for this):

In Chrome, my multiple-select widget is 150px wide, the same as the original select box. In IE11, it is 168px wide, which the width of the original select box plus padding and border.

I'm not sure which should be standardized on, but it is inconsistent as-is and caused some layout issues on my site.

**Comment by djhvscf** [comment]
Can you provide an example, please?

**Comment by Elvica** [comment]
Diferent Size example:
Firefox:
![imagen](https://cloud.githubusercontent.com/assets/6606058/21889859/43e6c268-d8cb-11e6-9c50-b2a7c2370530.png)

Chrome:
![imagen](https://cloud.githubusercontent.com/assets/6606058/21889869/5914e17e-d8cb-11e6-8d27-013f528e0a6c.png)

**Comment by wenzhixin** [comment]
Same issue with #142.
