### ISSUE TITLE
Overflow issue

### ISSUE THREAD

**Issue by irshadmb** [wenzhixin/multiple-select#288]
Hello, I am trying to add multiple select in a div  which is having a overflow:scroll but the drop down is within the div it has to appear outside the div. Can you please suggest me how to solve the issue.

https://jsfiddle.net/irshadmb/a3z5ccax/

**Comment by wenzhixin** [comment]
The `container` option can solve this problem: http://multiple-select.wenzhixin.net.cn/examples/#container.html
