### ISSUE TITLE
Groups don't get checked by default

### ISSUE THREAD

**Issue by itstudiocz** [wenzhixin/multiple-select#289]
With all values in a group selected when rendering the select, opt groups don't get checked:

http://jsfiddle.net/1ee00hej/

**Comment by hoang89** [comment]
same problem with me, cannot make it checked even set attribute checked to true

**Comment by hckiang** [comment]
The bug is fixed. @wenzhixin please take a look and pull.

**Comment by chatcoda** [comment]
@hckiang : unfortunately your fix is incomplete.
Here is mine (tested) : #346

**Comment by wenzhixin** [comment]
Tested and merged the PR, thanks @hckiang
