### ISSUE TITLE
An option to display optgroups names instead of list of options in the title

### ISSUE THREAD

**Issue by smartcorestudio** [wenzhixin/multiple-select#29]
I think that it also can be useful to have an option to display optgroup names instead of list of options in the title, when the whole groups were selected.
For example we can turn this:
![2013-11-21 10_48_52-multiple select](https://f.cloud.github.com/assets/2891792/1589752/8bdbe368-5279-11e3-882a-69aef3dbdf68.png)
into this
`[Group1], [Group3]`
instead of "Option1, Option2, Option3, Option7, Option..."
Optionally, it also can be displayed in the following way:
`[Group1: Option1, Option2], [Group3: Option7]`

**Comment by AllanPooley** [comment]
@wenzhixin 

Is it possible to disable this notation and use the original in your current release of multi-select?

**Comment by AllanPooley** [comment]
For anyone looking to have their selections appear as:

> Option 1, Option 2, Option 3

As opposed to:

> [Group1: Option1, Option2], [Group3: Option3]

You can change the following code (Line 560 to 570):

```javascript
html.push('[');
html.push(text);
if ($children.length > $selected.length) {
    var list = [];
    $selected.each(function () {
        list.push($(this).parent().text());
    });
    html.push(': ' + list.join(', '));
}
html.push(']');
texts.push(html.join(''));
```

To:

```javascript
// Modified to not include option groups in selected items text
if ($children.length > $selected.length) {
    var list = [];
    $selected.each(function () {
      list.push($(this).parent().text().trim());
    });
    html.push(list.join(', '));
}
texts.push(html.join(''));
```
