### ISSUE TITLE
Multiple Select 不显示checkbox

### ISSUE THREAD

**Issue by CHNDOUBLEL** [wenzhixin/multiple-select#300]
如题，无法显示可供勾选的checkbox，请问可能是什么原因？谢谢

**Comment by securenai** [comment]
是否可以分享你的程式碼?

**Comment by CHNDOUBLEL** [comment]
你好，十分感谢你的回复！由于假期回老家的原因，没能及时回复，十分抱歉！目前问题已经解决，原因是
multipel-select.css中checkbox的css样式被bootstrap的css样式覆盖了，导致checkbox无法显示。感谢百忙之中还能回复我的问题，谢谢！






在 2016-06-08 11:44:15，"securenai" <notifications@github.com> 写道：


是否可以分享你的程式碼?
