### ISSUE TITLE
Setting constructor SelectAllDelmimiter

### ISSUE THREAD

**Issue by M1K3Yio** [wenzhixin/multiple-select#301]
When setting the constructor selectAllDelimiter and replacing it with '' there is a extra space before the text ' Select all'.  Reviewing the JavaScript I noticed that in sprintf('<input type="checkbox" %s /> ', this.selectAllName).  Which makes the text not lineup.  I have created a jsfiddle with an example and a  jQuery hack of how I fixed this.  Is this an intended feature or a bug.  Also, if you would like to keep the space I think a span should be added.  This would simplify being able to style or use jQuery to change this data.  Similar to how all the other labels have span around the text.

https://jsfiddle.net/z7r7o6gx/3/

Thanks!

**Comment by wenzhixin** [comment]
Fixed in the latest version, thanks for the feedback.
