### ISSUE TITLE
Destroy for multipleSelect

### ISSUE THREAD

**Issue by legendvijay** [wenzhixin/multiple-select#304]
is there any way to Destroy functionality for multipleSelect

**Comment by roromix** [comment]
I have created a nice detroy method in PR#324 : https://github.com/wenzhixin/multiple-select/pull/324

**Comment by LukeMcLachlan** [comment]
This isn't working with the latest release, I'm getting the console error:
    Uncaught Unknown method: destroy
I'm calling destroy:
    $('#select1').multipleSelect('destroy');

**Comment by wenzhixin** [comment]
Fixed in the latest version:
http://multiple-select.wenzhixin.net.cn/examples/#destroy.html
