### ISSUE TITLE
redundant whitespace in "selectAll" input

### ISSUE THREAD

**Issue by floriancapelle** [wenzhixin/multiple-select#308]
I found a minor but annoying issue on this line in the init function:

``` javascript
...
sprintf('<input type="checkbox" %s /> ', this.selectAllName),
...
```

It happens when dynamically adding/removing options and refreshing the plugin afterwards.
I will provide a pull request.
I really like the plugin by the way, been a solution for some situations already.

**Comment by Pls** [comment]
This should be merged in, fixes the issue nicely! Thanks @floriancapelle!
