### ISSUE TITLE
No support for "required" select list

### ISSUE THREAD

**Issue by stevenbhn** [wenzhixin/multiple-select#314]
I have a select list with `multiple="multiple"` and `required="required"` attributes.

If no options selected the form fails to submit and not error or jump to question happens. Chrome inspector reports error that it cant focus on hidden element (original select).

I want the required message to appear and the viewport to jump to question as it does before the plugin is active.

Thanks

**Comment by junal** [comment]
I have same issue. Any solution?

**Comment by vielhuber** [comment]
Some update on this?

**Comment by wenzhixin** [comment]
Fixed in #480
