### ISSUE TITLE
Strange beahvior

### ISSUE THREAD

**Issue by maumau1001** [wenzhixin/multiple-select#322]
I use multiselect in IE8 (in compatibility mode).
I check select all (or a single check) and when the event end the checkbox loose the checked and return unckecked.
I check your code and the issue happen after the end of event.
The issue  not happen in IE 9/10/11 in compatibility mode .

SOLVED!.The issue happens where the SELECT has associated his own changhe handler. I remove the select handler and move the code in  onClick:

**Comment by wenzhixin** [comment]
If the problem exists reopen it.
