### ISSUE TITLE
Always visible

### ISSUE THREAD

**Issue by hmcab** [wenzhixin/multiple-select#327]
Hey wenzhixin,

First, thanks by the component, very useful. Now, is posible
get that multiple-select always stay deployed although you
click on it. The KeepOpen option allow a part, but it is hidden 
when I click on top.

Thanks..

**Comment by wenzhixin** [comment]
Workaround example: http://multiple-select-live.wenzhixin.net.cn/code/wenzhixin/749

Fixed in #476
