### ISSUE TITLE
calling checkAll method in onClick Event throwing error

### ISSUE THREAD

**Issue by kthanesh** [wenzhixin/multiple-select#328]
```
$("select").each(function(){
      if($(this).hasClass("multiSelectDD")){
		$(this).multipleSelect({
		            selectAll: false,
		            onClick: function(view){
						console.log(view.label + '(' + view.value + ') ' + 
			                    (view.checked ? 'checked' : 'unchecked'));
						if(view.value === "ALL"){
							$(this).multipleSelect('checkAll');
						}
						
					}
		        });
			}
});
```

$(this).multipleSelect('checkAll'); line of code throws 

Uncaught TypeError: Cannot read property 'createDocumentFragment' of undefined(…)

Please let me know what i am doing wrong here?

**Comment by GYY2046** [comment]
maybe you need this  $(view.instance.$.parent).parents("") to find the select element

**Comment by wenzhixin** [comment]
Fixed in the latest version: http://multiple-select-live.wenzhixin.net.cn/code/wenzhixin/467
