### ISSUE TITLE
'All Selected' defaults to Spanish when using Gems

### ISSUE THREAD

**Issue by fakefarm** [wenzhixin/multiple-select#332]
Hello, 

First off, this is a fantastic library. Great job! Thank you for all your hard work. We hit an issue that I'm honestly not sure where it originates. It happens on multiple machines and multiple Gems.  

I'm in a Rails app so I tried [renanoronfle/multiple_select_rails](https://github.com/renanoronfle/multiple_select_rails) and then switched to
[rails-assets-multiple-select](https://rails-assets.org/#/components/multiple-select) since it is the latest version. 

However, in both versions when I selected all options the default language was Spanish. I removed the gems and installed the `.js` and `.css` files directly and the Spanish went away. _Nothing wrong with Spanish, just sayin'_. Both Gems seem to be pointing directly to the lib and I don't see any options for additional behavior so I just thought I'd come here to submit the issue. 

I solved it with using options found in the [excellent docs](http://wenzhixin.net.cn/p/multiple-select/docs/)

```
  $('.multiple-select').multipleSelect({
    selectAll: false,
    allSelected: 'All selected',
    countSelected: '# of % selected',
  });
```

## Before Options Added
<img width="210" alt="screen shot 2016-12-02 at 3 02 13 pm" src="https://cloud.githubusercontent.com/assets/587705/20848500/64d30aae-b8a0-11e6-9650-785000619fb9.png">

_Todos Selecionados_

<img width="210" alt="screen shot 2016-12-02 at 3 02 19 pm" src="https://cloud.githubusercontent.com/assets/587705/20848506/6a10ae40-b8a0-11e6-9e62-0608886e6f37.png">

_4 of 5 selecionados_ 

##  After Options Added
<img width="210" alt="screen shot 2016-12-02 at 3 02 26 pm" src="https://cloud.githubusercontent.com/assets/587705/20848511/6f78fafe-b8a0-11e6-9441-9ff74303a677.png">
<img width="206" alt="screen shot 2016-12-02 at 3 02 32 pm" src="https://cloud.githubusercontent.com/assets/587705/20848518/736d9d5e-b8a0-11e6-9ea0-4b5406b111a7.png">

Hope that helps.

**Comment by Xefiron** [comment]
Hi, I know that a lot of time has passed since this question, but I would like to contribute also by complementing your solution. In the class "multiple-select.js" you must go down to line 739, from there to line 742 there are the names that are shown to the user in the drop-down list, just edit the string so that it applies to all the select from this library. Good day.

**Comment by fakefarm** [comment]
Thanks!
