### ISSUE TITLE
Stale External Resources for JSFiddle examples?

### ISSUE THREAD

**Issue by gtzl258** [wenzhixin/multiple-select#333]
It looks like some of the JSFiddle examples have stale **External Resources**. I can look into updating them if that's possible. (e.g. the **Basic Example** works only if I update the .js file to http://wenzhixin.net.cn/p/multiple-select/multiple-select.js and the .css file to http://wenzhixin.net.cn/p/multiple-select/multiple-select.css). Thanks

**Comment by wenzhixin** [comment]
Examples: http://multiple-select.wenzhixin.net.cn/examples/#basic.html
