### ISSUE TITLE
Limit the max of item shown

### ISSUE THREAD

**Issue by daltondiaz** [wenzhixin/multiple-select#337]
Hello everyone,

I need to limit the numbers of items shown. So my select has 1000 items and I show only 30, but if I searching for a item which dont can be between the 30 should show it.

This help us in the performance the View because don't need to render the 1000 elements.

**Comment by wenzhixin** [comment]
It's the same feature with #360.

**Comment by nick-yushenko** [comment]
So do we have some solution to this problem? 
In my case I need to load around 8-9 thousand items and it works too low
