### ISSUE TITLE
Uncaught TypeError: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by Shahjalal7311** [wenzhixin/multiple-select#339]
Uncaught TypeError: Cannot read property 'find' of undefined
    at b.updateStatus (bootstrapValidator.min.js:11)
    at b.validateField (bootstrapValidator.min.js:11)
    at b.validate (bootstrapValidator.min.js:11)
    at HTMLFormElement.<anonymous> (bootstrapValidator.min.js:11)
    at HTMLFormElement.dispatch (jquery.min.js:3)
    at HTMLFormElement.r.handle (jquery.min.js:3)

Form 
<div class="large-5 medium-5 columns">
                        <div class="input college_code">
                            <?php
                            
                                echo $this->Form->input('college_code', [
                                    'label' => false, 'class' => 'form-control','required' => true
                                    ,'data-bv-notempty-message'=>'"college code" is mandatory & can&#39;t be empty'
                                    ,'data-bv-notempty'=>'true' ,'placeholder'=>'Enter college code', 'data-bv-field'=>'college_code']);
                            ?>
                           <i style="display: none; top: 0px;" class="form-control-feedback" data-bv-icon-for="college_code"></i>
                         </div> 
                        <small style="display: none;" class="help-block" data-bv-validator="notEmpty" 
                               data-bv-for="college_code" data-bv-result="NOT_VALIDATED">
                            "college code" is mandatory & can't be empty
                        </small>
                        <small style="display: none;" class="help-block" data-bv-validator="stringLength" 
                               data-bv-for="college_code" data-bv-result="NOT_VALIDATED">Enter your college code
                        </small>
                    </div>

how can fix it?

**Comment by wenzhixin** [comment]
Fixed in the latest version.

**Comment by Jatinghataliya** [comment]
@wenzhixin in which version?

**Comment by qiuliliang** [comment]
sometime this same error happen, don't know why
