### ISSUE TITLE
Filter is not searching for disabled options

### ISSUE THREAD

**Issue by programmersujeet** [wenzhixin/multiple-select#342]
I have a dropdown list having some disabled options. 
When I am setting filter option to true, its enabling the searching functionality but all the disabled options are not getting searched.
**HTML**
`<select>`
`	<option>1</option>`
`	<option disabled="true">2</option>`
`	<option>3</option>`
`	<option>4</option>`
`	<option>5</option>`
`</select>`
**JavaScript**
`$('select').multipleSelect({`
`    	filter: true,`
`		placeholder: '-------- Select value(s) --------'`
`    });`

**Comment by wenzhixin** [comment]
The filter is not supported disabled options.
