### ISSUE TITLE
{improvement} Unselect cross icon to unselect items

### ISSUE THREAD

**Issue by gtrdblt** [wenzhixin/multiple-select#344]
Hi, 

Would it be possible for you to add a button/icon to allow users to unselect all items ? For example juste after the ms-search input ?

Thank you.

Sincerly,

Gautier

**Comment by david-ieong** [comment]
Hi,

I need this improvement too.

When I'm in radio mode I can't unselect the item.

Thank you.

David

**Comment by wenzhixin** [comment]
Fixed in #500
