### ISSUE TITLE
Checkboxes not appearing

### ISSUE THREAD

**Issue by SPlatten** [wenzhixin/multiple-select#345]
I've downloaded the latest script and I don't get any checkboxes.  I have the following scripts, in this order:

<script type="text/javascript" src="/scripts/modernizr.js"></script>
<script type="text/javascript" src="/scripts/genetic.js"></script>
<script type="text/javascript" src="/scripts/jquery/jquery-2.2.1.min.js"></script>
<script type="text/javascript" src="/scripts/jquery/jquery-ui.min.js"></script>
<script type="text/javascript" src="/scripts/jquery/multisel/multiple-select.js"></script>
<script type="text/javascript" src="/scripts/jquery/tablesorter/js/jquery.tablesorter.js"></script>
<script type="text/javascript" src="/scripts/jquery/tablesorter/js/jquery.tablesorter.widgets.js"></script>
<script type="text/javascript" src="/scripts/jquery/tablesorter/js/widgets/widget-scroller.js"></script>
<script type="text/javascript" src="/scripts/jquery/tablesorter/addons/pager/jquery.tablesorter.pager.js"></script>
<script type="text/javascript" src="/scripts/jquery/dateentry/jquery.plugin.min.js"></script>
<script type="text/javascript" src="/scripts/jquery/dateentry/jquery.datetimeentry.min.js"></script>
<script type="text/javascript" src="/scripts/jquery/inputmask3.x/js/jquery.inputmask.js"></script>
<script type="text/javascript" src="/scripts/jquery/jqwidgets/jqxcore.js"></script>
<script type="text/javascript" src="/scripts/jquery/jqwidgets/jqxbuttons.js"></script>
<script type="text/javascript" src="/scripts/jquery/jqwidgets/jqxscrollbar.js"></script>
<script type="text/javascript" src="/scripts/jquery/jqwidgets/jqxlistbox.js"></script>
<script type="text/javascript" src="/scripts/jquery/jqwidgets/jqxcombobox.js"></script>
<script type="text/javascript" src="/scripts/jquery/jqwidgets/jqxpasswordinput.js"></script>
<script type="text/javascript" src="/scripts/jquery/jqwidgets/jqxbuttons.js"></script>
<script type="text/javascript" src="/scripts/jquery/jqwidgets/jqxmenu.js"></script>
<script type="text/javascript" src="/socket.io/socket.io.js"></script>
<script type="text/javascript" src="/svr/defs.js"></script>

I cannot see any errors or warnings in the debugger, can anyone help?

**Comment by wenzhixin** [comment]
Hi! We are going to close this issue because it's 2 years ago. If you need help please reopen and provide an example. Thanks!
