### ISSUE TITLE
Should only set the value of inner input

### ISSUE THREAD

**Issue by zhaoruda** [wenzhixin/multiple-select#351]
在这一行代码中：https://github.com/wenzhixin/multiple-select/blob/master/multiple-select.js#L277
我们应该给内部的input赋值个标识，然后只修改内部input的值。
例如：
$('#select-multi-file').multipleSelect({
        textTemplate: function ($el) {
            return $el.html() + "<input type='text' placeholder='1' style='margin-left:10px'>";
        }
    });

这样就会导致，无法传递input了。

**Comment by wenzhixin** [comment]
这里的 $el 是原来的 `<option>`，例子：http://multiple-select.wenzhixin.net.cn/examples/#text-template.html

假如问题还存在的话重新打开问题。
