### ISSUE TITLE
Setting json collection as datasource to list

### ISSUE THREAD

**Issue by sairfan1** [wenzhixin/multiple-select#352]
I was looking for some solution, I want to set ajax result to list, something like this
`        $.get("/GetData/GetOptions", function (data) {
            $('select').multipleSelect({
                width: 300,
                filter: true,
                datasource: data
            });
            });
        });`

**Comment by rakhiattal** [comment]
Did you find Solution to this ??

**Comment by wenzhixin** [comment]
Fixed in #445 
http://multiple-select-live.wenzhixin.net.cn/code/wenzhixin/465
http://multiple-select-live.wenzhixin.net.cn/code/wenzhixin/466
