### ISSUE TITLE
Sending the selected results in a row

### ISSUE THREAD

**Issue by jschwenk081** [wenzhixin/multiple-select#353]
Hi,

using multiple select sends the selected results as an array, e.g. value=1&value=2&value=3

How is it possible to send all selected results in one string delimited by a comma, e.g. Value=1,2,3

Thanks for reply!
Juergen

**Comment by wenzhixin** [comment]
Working example: http://multiple-select-live.wenzhixin.net.cn/code/wenzhixin/455
If the problem exists please reopen it.
