### ISSUE TITLE
Wrong count of selected item, when filtering by groups

### ISSUE THREAD

**Issue by leonardobegher** [wenzhixin/multiple-select#355]
When you add groups, and filter by them. If you select 31 of 33 items, and request the text, they show a wrong count. They count the number of groups selected, on the total number of items. Instead the number of items over number of items.

![image](https://user-images.githubusercontent.com/8462292/30809293-a0a1b2b2-a1d7-11e7-9a42-5cbaf4024821.png)

**Comment by LuanMaik** [comment]
same problem here.

**Comment by bcavileer** [comment]
same here

**Comment by aleman111** [comment]
@LuanMaik  @bcavileer  In this fork it works
