### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by pkduffy2014** [wenzhixin/multiple-select#356]
Running in chrome. The drop down is not displaying properly. Replaced my index with the one from the demo and put all the files in the root directory. 
Do you have some install directions? Still learning the whole process. Installing on an existing website...
Any help would be appreciated. 
Paul

![image](https://user-images.githubusercontent.com/9505118/31034682-f91ec660-a519-11e7-838d-5fba8a5d9f50.png)

![image](https://user-images.githubusercontent.com/9505118/31034760-44336688-a51a-11e7-9645-9fe5113d92b0.png)

**Comment by wenzhixin** [comment]
You need to import jQuery: http://multiple-select.wenzhixin.net.cn/getting-started/#usage
