### ISSUE TITLE
when the data list items more than 10000 and call the function multiSelect('refresh') very very slow

### ISSUE THREAD

**Issue by manmanwu18** [wenzhixin/multiple-select#360]
when the data list items more than 10000 and call the function multiSelect('refresh') very very slow，is there has pagination for the huge data

**Comment by LuanMaik** [comment]
I would suggest to use any autocomplete plugin with ajax search options instead <select>.

**Comment by wenzhixin** [comment]
Fixed in #503
Added virtual scroll to support large data: http://multiple-select-live.wenzhixin.net.cn/code/wenzhixin/953
