### ISSUE TITLE
[Integrate with React] The first option is always "selected" while created

### ISSUE THREAD

**Issue by ted-lee** [wenzhixin/multiple-select#361]
I want to integrate multi-select into my react project as a react component.
After following the [react guide](https://reactjs.org/docs/integrating-with-other-libraries.html),
I found the first option in multi-select is a always "selected" while created.
I cannot find anything wrong in my integration, I think the problem is caused by multi-select. 
Below is a simple code pan I did:
https://codepen.io/ted-lee/pen/aVbJda

**Comment by barrywoolgar** [comment]
I had this problem when I forgot to set the `multiple` attribute on the `<select>` element. 

Looking at your codepen, your `<Example />` component doesn't set this attribute either.

**Comment by wenzhixin** [comment]
@barrywoolgar is right, you can add `multiple` attribute to solve the problem, in the latest version, you can use `data` instead without multiple attribute: http://multiple-select-live.wenzhixin.net.cn/code/wenzhixin/569.
