### ISSUE TITLE
How to uncheck single option?

### ISSUE THREAD

**Issue by erwandy92** [wenzhixin/multiple-select#364]
I find hard to do the single uncheck to multiselect option,
Could you please provide an solution for this?

Thank you

**Comment by Sanitator** [comment]
Simple ad hoc function based on coding I did today,

var removeOption = function (value) {  
    var choices = $("select").multipleSelect("getSelects"); // Returns array of selected options  [ "Foo", "Bar" ];
    var index = choices.indexOf(value);
    
    if (index > -1) {
        choices.splice(index, 1); // Remove option
        $("select").multipleSelect("setSelects", choices);
    }
};

Use arguments which match the values of options you wish to remove. This was confusing, as the example for setSelect at the plugin homepage implied you have to use array indexes as arguments instead, but that didn't work for me. Strings worked just fine.

**Comment by wenzhixin** [comment]
In the latest version, we can use `uncheck` method to do this: http://multiple-select.wenzhixin.net.cn/examples#check-uncheck.html

**Comment by wenzhixin** [comment]
Fixed in #500

**Comment by erwandy92** [comment]
Thank you so much.. 謝謝！
