### ISSUE TITLE
 Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`

### ISSUE THREAD

**Issue by yatin13490** [wenzhixin/multiple-select#368]
I used multiple-select with NPM when I compiled this it gives me an error:

WARNING in ./node_modules/css-loader??ref--8-2!./node_modules/postcss-loader/lib??postcss!./node_modules/multiple-select/multiple-select.css
(Emitted value instead of an instance of Error) autoprefixer:...Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`

how to fix this?

**Comment by Chrysweel** [comment]
+1 
I have the same problem

```
Running webpack ...

 WARNING  Compiled with 1 warnings                                                                                                                        09:56:54

 warning  in ./node_modules/multiple-select/multiple-select.css

Warning

(129:5) Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.

 @ ./node_modules/multiple-select/multiple-select.css 2:14-122
```

@yatin13490 did you fix the problem?

**Comment by Chrysweel** [comment]
I think that this pull request fix the problem.

https://github.com/wenzhixin/multiple-select/pull/400

cc @wenzhixin

**Comment by Chrysweel** [comment]
@wenzhixin 我认为这个拉取请求解决了这个问题。

(I used google translate sorry for my language)

**Comment by wenzhixin** [comment]
Merged into develop branch.
