### ISSUE TITLE
onClose event blocking Angular 5 change detection module

### ISSUE THREAD

**Issue by PT10** [wenzhixin/multiple-select#373]
Is there something peculiar about the onClose event? When I extended it to invoke my code on closing the drop down (by clicking outside), Angular's ngOnChanges is not getting triggered until I click somewhere on the page.  Interestingly if i use escape key to close the dropdown, ngOnChanges works just fine. My code is as follows.

<select multiple="multiple" style="font-size: 12px !important" #multiselect>
			        	<option value="0">0</option><option value="1">1</option></select>

$(me.multiselect.nativeElement).multipleSelect({
            width: 120,
            multiple: true,
            multipleWidth: 60,
            
            onClose: function() {
              let selectedHrs = $(me.multiselect.nativeElement).multipleSelect('getSelects');
              
              me.eventService.publish(EventNames.CHART_DATE_CHANGED, me.newSelectedDateArr);
            }
        });

**Comment by PT10** [comment]
After spending 1 and half days Figured out the issue. In function MultiSelect, click event is bound to the document and is never unbound. After changing it to 
 $(document).**off('click')**.on('click',function (e) 

everything started working.

**Comment by ghiscoding** [comment]
@PT10 
Oh my god, thank you so much, I have been looking to fix since forever. Thank you so much!!!

**Comment by PT10** [comment]
@ghiscoding 
My pleasure.

> @PT10
> Oh my god, thank you so much, I have been looking to fix this weird behavior since forever. Thank you so much!!!

**Comment by ghiscoding** [comment]
@PT10 
I actually found out that `.off('click')` is not that good in itself since it completely remove the click features for all other libraries (like Bootstrap and navbar menu in my case). A better way of fixing this is to give a namespace to the event, so in my case I had to change it for
```js
$(document).off('click.multiple-select').on('click.multiple-select', function (e) {
  // ...
});
```
Using namespace in the event doesn't interfere with anything else.

**Comment by ghiscoding** [comment]
I finally found the best working solution, it doesn't have any known side effect (finally). 

```js
$('body').click(function (e) {
  // ... 
});
```
So I'm basically using the last code [here](https://github.com/wenzhixin/multiple-select/blob/7baa9c7793df238e50ee02d370a1570e782ae213/multiple-select.js#L178) but changing the `$(document)` to `$('body')` and that's it, it finally works with Angular 7 like it should.
