### ISSUE TITLE
single true the multipleSelect('getSelects', 'text')) has a bug

### ISSUE THREAD

**Issue by Scovin** [wenzhixin/multiple-select#375]
$('#X').multipleSelect({
  single: true,
  multipleWidth: 100,
  placeholder: "None Selected",
  onClick: function(view){
    X = JSON.stringify($('#X').multipleSelect('getSelects', 'text'));
  }
for example there is a selector with two options: 1. marry 2. cindy
first , I choose marry. actually , I want to choose cindy. Hence, I change it at once.
I console.log(X) and show ["marry","cindy"]. I just want to "cindy" . Could you provide some moethods for this question. thank u

**Comment by iniakunhuda** [comment]
Same issue here.

**Comment by nop1984** [comment]
Try this may be

https://github.com/wenzhixin/multiple-select/pull/370

**Comment by wenzhixin** [comment]
Merged #370 into develop branch.
