### ISSUE TITLE
setSelects not assigning values from array variable

### ISSUE THREAD

**Issue by richarddsouzabluemarksoft** [wenzhixin/multiple-select#376]
Hi.

I am trying to setSelects value by passing an array of strings to it. But only the first value is getting selected in the dropdown.

$("#ddlCity").multipleSelect({
filter: true,
placeholder: "None selected",
width: "100%"
});

$("#ddlCity").multipleSelect('setSelects', selectedCities); //selectedCities contains an array of string.

When I pass a hardcoded array then the drop down selection is working fine, but when I pass an array variable than only the first index value gets selected.
If i pass data as
$("#ddlCity").multipleSelect('setSelects', ["New York", "London"]);

it seems to work.

**Comment by wenzhixin** [comment]
It seems working fine in the latest version: http://multiple-select.wenzhixin.net.cn/examples/#setSelects-getSelects.html.
If the problem exists please reopen it and please provide an [Online Example](http://multiple-select-live.wenzhixin.net.cn) to show the problem, thanks!
