### ISSUE TITLE
Issue on Ajax option create

### ISSUE THREAD

**Issue by anojsaranga** [wenzhixin/multiple-select#379]
I am creating the select box dynamically via ajax and added multipleSelect('refresh'); But it says
TypeError: $(...).append(...).multipleSelect is not a function. 

This is my code:

$('input:checkbox').on('change', function()
		{
			$('[name="selectItemad_category[]"]').each(function () 
			{
				if ($(this).is(':checked')) 
				{
					var category_id = $(this).val();

					var dataSet = {
						action       : 'get_sub_category',
						cat_id       : category_id,
						submitMode   : 'ajax'
					};

					var dataSentUrl = base_url+'myaccount/manageSubCategory.php';

					//jquery. ajax function
					jQuery.ajax({
				        type     : "post",
				        url      : dataSentUrl,
				        dataType : 'json',
				        data     : dataSet ,
				        success  : function (res)
				        {
				        	if (res.status == 'success')
				        	{
				        		for(index=0; index<res.options.length; index++)
				        		{
				        			$('#ad_sub_category').append('<option value="'+res.options[index].id+'" >'+res.options[index].name+'</option>').multipleSelect("refresh");;
				        		}
				        	}
				        }			//success  : function (res)
			    	});		//jquery. ajax function
                }
            });
		
		});

Could you please help me?

Thank you

**Comment by wenzhixin** [comment]
Added `data` support in #445.
