### ISSUE TITLE
Select All with optgroup

### ISSUE THREAD

**Issue by nitincdac** [wenzhixin/multiple-select#382]
Hello

"Select All" is showing the Select All label in the text box, when using with with optgroup. 
If am using the optgroup & then click on the "Select All", then in the text box it is not showing the "All Selected", instead it is showing the count like "5 of 100 selected", where 5 is the group count & 100 is the items inside these groups.  

Regards

**Comment by wenzhixin** [comment]
Fixed in the latest version: http://multiple-select.wenzhixin.net.cn/examples#basic-optgroups.html
