### ISSUE TITLE
How to hide radio buttons for single select?

### ISSUE THREAD

**Issue by AP-TGR** [wenzhixin/multiple-select#386]
I am using your multi-select as single select to use the search functionality. I don't want to display the radio button. Can you suggest some better approach to hide it? Currently, I am using CSS to hide the input element.
`jQuery('input[type="radio"]').data('name','selectItems+elementname').css("display","none");`

**Comment by Yzchen1994** [comment]
My client also has the same requirement. @wenzhixin Are you able to add an option to hide radio button?

**Comment by Guaze** [comment]
Do it:

optionToHtml: function (i, elm, group, groupDisabled) {
...
...
...

$el = $([
                    sprintf('<li class="%s %s" %s %s>', multiple, classes, title, style),
                    sprintf('<label class="%s">', disabled ? 'disabled' : ''),
                    **sprintf('<input type="%s" %s%s%s%s%s>',**
                        type, this.selectItemName,
                        **type === 'radio' ? 'hidden=true': '',**
                        selected ? ' checked="checked"' : '',
                        disabled ? ' disabled="disabled"' : '',
                        sprintf(' data-group="%s"', group)),
                    sprintf('<span>%s</span>', text),
                    '</label>',
                    '</li>'
                ].join(''));

**Comment by Guaze** [comment]
para a versão 1.3.1

//var $el = $([sprintf(_templateObject11(), s, s, s, s)(multiple, classes, title, style), sprintf(_templateObject12(), s)(disabled ? 'disabled' : ''), sprintf(_templateObject13(), s, s, s, s, s)(type, this.selectItemName, selected ? ' checked="checked"' : '', disabled ? ' disabled="disabled"' : '', sprintf(_templateObject14(), s)(group)), sprintf(_templateObject15(), s)(text), '</label>', '</li>'].join(''));

          var $el = $([sprintf(_templateObject11(), s, s, s, s)(multiple, classes, title, style), sprintf(_templateObject12(), s)(disabled ? 'disabled' : ''), sprintf(_templateObject13(), s, s, s, s, s, s)(type, this.selectItemName, type === 'radio' ? 'style="display:none"' : '', selected ? ' checked="checked"' : '', disabled ? ' disabled="disabled"' : '', sprintf(_templateObject14(), s)(group)), sprintf(_templateObject15(), s)(text), '</label>', '</li>'].join(''));

**Comment by wenzhixin** [comment]
Fixed in #456
