### ISSUE TITLE
optgroup doesn't select parent group when select all children from that group

### ISSUE THREAD

**Issue by digvijay-17** [wenzhixin/multiple-select#393]
Updated this code to resolve the problem:
selected = true;
                $.each($elm.children(), function (i, elm) {
                    selected = selected && $(elm).prop('selected');
                });
                $group.append([
                    '<li class="group">',
                    sprintf('<label class="optgroup %s" data-group="%s">', disabled ? 'disabled' : '', group),
                    this.options.hideOptgroupCheckboxes || this.options.single ? '' :
                        sprintf('<input type="checkbox" %s %s %s>',
                        this.selectGroupName, disabled ? 'disabled="disabled"' : '', selected ? 'checked="checked"' : ''),
                    label,
                    '<span class="checkmark"><span>',
                    '</label>',
                    '</li>'
                ].join(''));

**Comment by wenzhixin** [comment]
Fixed in #346
