### ISSUE TITLE
2 muti select selectbox same page

### ISSUE THREAD

**Issue by cocolee** [wenzhixin/multiple-select#395]
Hi;
first of all thank you so much for plugin.
can i use 2 multi select selectbox on same page?

i try to use 
$('#id1').multipleSelect();
$('#id2').multipleSelect();

and when i click list item on id2 it's affected id1.

i hope i'll be explain.

thanks again

**Comment by wenzhixin** [comment]
Added to the example: http://multiple-select.wenzhixin.net.cn/examples/#two-select.html
