### ISSUE TITLE
Multiple definitions of a property not allowed in strict mode

### ISSUE THREAD

**Issue by SamLNL** [wenzhixin/multiple-select#396]
Hello,

I'm getting this error in IE11:

`Multiple definitions of a property not allowed in strict mode`

I already checked the code, and noticed there are two 'destroy' functions.
Check the `multiple-select.js` file:

![screenshot at jan 07 11-57-15](https://user-images.githubusercontent.com/21331474/50764568-682f9a80-1273-11e9-81b6-5ccbd6699587.png)

**Comment by jhermiz** [comment]
I can take a look at this.

**Comment by jhermiz** [comment]
I put a pull request in https://github.com/wenzhixin/multiple-select/pull/399

**Comment by meersonv** [comment]
Please pull new version ASAP. Because this bug it's impossible to use optgroups in IE10 and IE11 (including http://multiple-select.wenzhixin.net.cn/home/ site).

**Comment by wenzhixin** [comment]
Merged into develop branch.
