### ISSUE TITLE
selectAllText/allSelected doesn't work properly

### ISSUE THREAD

**Issue by kgansberger** [wenzhixin/multiple-select#397]
http://jsfiddle.net/cfmwsua8/

**Comment by JackZhouMine** [comment]
I met the same problem.

**Comment by jhermiz** [comment]
Can you provide more information like what browser you are using, seems to work in latest stable versions of chrome and edge.

**Comment by bomastudioweb** [comment]
I solved by changing these lines, i used data attributes in my case it worked
<pre>

-                $span.removeClass('placeholder').html(this.options.formatAllSelected);
+                $span.removeClass('placeholder').html(this.options.formatAllSelected());

-                    .join(this.options.delimiter) + '...');
+                    .join(this.options.displayDelimiter) + '...');

-                $span.removeClass('placeholder').text(selects.join(this.options.delimiter));
+                $span.removeClass('placeholder').text(selects.join(this.options.displayDelimiter));

-        allSelected: true,

-            return '[Select all]';
+            if (typeof(this.selectAllText) === undefined)
+                return '[Select all]';
+            return this.selectAllText;

-            return 'All selected';
+            if (typeof(this.allSelected) === undefined)
+                 return 'All selected';
+            return this.allSelected;

-            return '# of % selected';
+            if (typeof(this.countSelected) === undefined)
+                return '# of % selected';
+            return this.countSelected;
</pre>
