### ISSUE TITLE
How to Fill multi select values by ajax

### ISSUE THREAD

**Issue by rakhiattal** [wenzhixin/multiple-select#401]
I am returning $op string in PHP 
```
while ($row = $result2->fetch_assoc()) {
        
       $op .= '<option value="'.$row["id"].'">'.$row["name"].'</option>';
    } 
```

and displaying this in JS , here data = $op
 ```
$('#ms').multipleSelect({
                        html: data
                    });

```
but data is not getting displayed. Please help

**Comment by IkeyBenz** [comment]
I'd also like the ability to dynamically change multi-select options onOpen, for efficiency purposes.

**Comment by shofer4eto** [comment]
Hey,

I actually managed to do this firing using the onFocus event.
In it first disable the multipleSelect, do the Ajax, upon its response enable the multipleSelect, then refresh it. 

```
	$select.multipleSelect('enable');
	$select.multipleSelect('refresh');
	$select.multipleSelect('open');
```
