### ISSUE TITLE
Duplicate key 'destroy'

### ISSUE THREAD

**Issue by TNChalise** [wenzhixin/multiple-select#403]
Currently the plugin has two keys "destroy".
Has to be removed or renamed as per their usage.

Here is the eslint error:
` 684:9  error  Duplicate key 'destroy'  no-dupe-keys`

Due to this, it stops working in IE10.

**Comment by meersonv** [comment]
Duplicates #396

**Comment by varik-kos** [comment]
the error is not fixed !!!

**Comment by TNChalise** [comment]
I could have created pull request, but this repo seems to be inactive. There are almost 30 pull requests..
