### ISSUE TITLE
IE 11 crashing completely, while working fine on Chrome

### ISSUE THREAD

**Issue by aifazk** [wenzhixin/multiple-select#407]
multiple select list breaking on IE(11) and browser console gives below error:
: Multiple definitions of a property not allowed in strict mode
multiple-select.js (682,16)
SCRIPT438: Object doesn't support property or method 'multipleSelect'
eval code (23) (2,5)
please use below url on IE to reproduce issue:
http://multiple-select.wenzhixin.net.cn/examples/#basic.html
while on google chrome and IE edge working fine.
pls suggest how to fix it
![image](https://user-images.githubusercontent.com/49869251/56499779-88573280-64cd-11e9-871a-b4630f5c5de9.png)

**Comment by alexnovelli** [comment]
Same problem here. Some help please?

**Comment by alexnovelli** [comment]
> multiple select list breaking on IE(11) and browser console gives below error:
> : Multiple definitions of a property not allowed in strict mode
> multiple-select.js (682,16)
> SCRIPT438: Object doesn't support property or method 'multipleSelect'
> eval code (23) (2,5)
> please use below url on IE to reproduce issue:
> http://multiple-select.wenzhixin.net.cn/examples/#basic.html
> while on google chrome and IE edge working fine.
> pls suggest how to fix it
> ![image](https://user-images.githubusercontent.com/49869251/56499779-88573280-64cd-11e9-871a-b4630f5c5de9.png)

Disable strict mode and works fine in IE11 ;)

**Comment by aifazk** [comment]
it worked on IE 11 too after removing, 'use strict' from multiple-select.js
Thanks
