### ISSUE TITLE
MultiSelect Checkbox Postback Issue

### ISSUE THREAD

**Issue by SriFNDR** [wenzhixin/multiple-select#417]
Hi,

I am using multiselect checkbox filter with search option. My browser is IE 8. When I select items on multiselect control and click on a button, all the selected items will disappear. I think this is due to the postback event happening due to the button click. Could you please help out on this.
I tried to rebind the items by getting the selected item from control. but it didn't work. Here is the code snippet. Only one item was getting selected

**Solution :1** 
```js
var arryselecteitems = $("#dropdowid").multipleSelect('getSelects', 'text')
    for(var i=0 ;i<arryselecteitems .length;i++)
          {
                   	
              	$('#dropdowid').multipleSelect('setSelects',  [arryselecteitems [i]]);
           }
  $('#dropdowid').multipleSelect('refresh');
```

**Solution : 2**
Other than the above solution i used the below 
Reference Link :https://github.com/wenzhixin/multiple-select/issues/367
```js
$("#chapterID").siblings(".ms-parent").remove();
```
And then clear associated JQuery data attached to the select element
```js
$("#chapterID").removeData();
```
Then I could reinstate a new multiple selection instance of a different selection type
e.g. your

```js
var chapter = jQuery('#chapterId').multipleSelect({
  filter: true,
  single: false;
});
```
But this keeps on adding new controls on button click, as we are intializing new instance.

**Comment by wenzhixin** [comment]
Added `refreshOptions` method to solve the problem.
Fixed in #458
