### ISSUE TITLE
allSelected and selectAllText still not working

### ISSUE THREAD

**Issue by hclojacky** [wenzhixin/multiple-select#433]
I have done a sample in Codepen.
Is there anything I did wrong or it really didn't work?

https://codepen.io/anon/pen/YbeVZv

**Comment by wenzhixin** [comment]
In the latest version, need to use `format[Name]` instead.

Example: http://multiple-select.wenzhixin.net.cn/examples/#i18n.html

```js
      $('#select').multipleSelect({
          width: 500,
          formatAllSelected: function () { 
            return 'All select nothing to show' 
          },
          formatSelectAll: function () {
            return 'Select'
          }
      })
```

Sorry for this, I will update the documentation ASAP.

**Comment by hclojacky** [comment]
thanks for your immediate help! save my life.
cheers

but how about doing this in "data-" attributes?
or it is not possible?

**Comment by wenzhixin** [comment]
In current version it does not support.

**Comment by hclojacky** [comment]
understood, thanks!

**Comment by wenzhixin** [comment]
Updated the docs in #436.
