### ISSUE TITLE
Open On Hover have problem

### ISSUE THREAD

**Issue by changingshow** [wenzhixin/multiple-select#434]
如果有两个 Select，同时开启openOnHover: true，当鼠标经过其中一个的时候，会把两个 Select都展开
![微信截图_20190524171453](https://user-images.githubusercontent.com/7709440/58317322-20876500-7e48-11e9-8860-d71c677d8645.png)
![微信截图_20190524171813](https://user-images.githubusercontent.com/7709440/58317328-22e9bf00-7e48-11e9-8d5f-a320f996ed56.png)
![微信截图_20190524171824](https://user-images.githubusercontent.com/7709440/58317336-2715dc80-7e48-11e9-9c2e-24d6da176604.png)

**Comment by wenzhixin** [comment]
Fixed in #435 
已修复

**Comment by changingshow** [comment]
> Fixed in #435
> 已修复到 develop 分支，需要等下个版本

好的。谢谢。
