### ISSUE TITLE
formatCountSelected not working?

### ISSUE THREAD

**Issue by hclojacky** [wenzhixin/multiple-select#438]
http://multiple-select.wenzhixin.net.cn/examples/#i18n.html

From the doc it changed 'count' and 'total'
But it seems still not working if i am using as return function:
formatCountSelected() {
   return \`count ${counterText}\`;
},

**Comment by wenzhixin** [comment]
Thanks for your feedback.
Updated the example: http://multiple-select.wenzhixin.net.cn/examples/#i18n.html
