### ISSUE TITLE
Internet Explorer : L’objet ne gère pas la propriété ou la méthode « includes »

### ISSUE THREAD

**Issue by eltharin** [wenzhixin/multiple-select#439]
includes function is not supported by Internet Explorer (https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/String/includes).
Just add these lines (for me at the end of multiple-select.js)

`if (String.prototype.includes == undefined)
{
	String.prototype.includes = function (str) 
	{
		return this.indexOf(str) !== -1;
	}
}`

**Comment by wenzhixin** [comment]
Thanks for your feedback.

**Comment by eltharin** [comment]
No problem !

I did’nt know where it’s the best to put this function so i didn’t do a PR.



De : 文翼 <notifications@github.com>
Envoyé : mercredi 5 juin 2019 10:58
À : wenzhixin/multiple-select <multiple-select@noreply.github.com>
Cc : eltharin <eltharin18@hotmail.fr>; Author <author@noreply.github.com>
Objet : Re: [wenzhixin/multiple-select] Internet Explorer : L’objet ne gère pas la propriété ou la méthode « includes » (#439)


Thanks for your feedback.

**Comment by wenzhixin** [comment]
Merged to the develop branch and will fix in the next version.
