### ISSUE TITLE
Crash view on modal-Form, after validation

### ISSUE THREAD

**Issue by Fruchtgummi** [wenzhixin/multiple-select#441]
I start a modal with form

![image](https://user-images.githubusercontent.com/2059888/60152081-76e91a00-97df-11e9-9f7a-f701a50898ec.png)

I press button to send form-data to my backend, the validation is fail and the selectbox crash.

![image](https://user-images.githubusercontent.com/2059888/60152151-b283e400-97df-11e9-83cf-a2e2addad912.png)

I think the script-selectbox and the regular selebox are shown.

How can I handle this?

**Comment by wenzhixin** [comment]
@Fruchtgummi Can you help to provide an [Online Example](http://multiple-select-live.wenzhixin.net.cn/) to show your problem with our latest version? Thanks!

**Comment by Fruchtgummi** [comment]
@wenzhixin sry, that problem came from other script...

**Comment by wenzhixin** [comment]
Thanks for your reply.
