### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Guaze** [wenzhixin/multiple-select#443]
I changed it ($.fn.multipleSelect):

if (!data) {
   data = new MultipleSelect($this, options);
   $this.data('multipleSelect', data);
} else {
   $.extend(data.options, $this.data(), typeof option === 'object' && option);
}

and too

if (typeof option === 'string') {
....
 } else {
   data.init();
   if (args[1]) {
      value = data[args[1]].apply(data, [].slice.call(args, 2));
   }
}

to override the target all the time.

**Comment by wenzhixin** [comment]
Thanks for your suggestion: https://github.com/wenzhixin/multiple-select/blob/develop/src/multiple-select.js
