### ISSUE TITLE
Any way to only select/send the parent optgroup value, when all children are selected?

### ISSUE THREAD

**Issue by noc2spam** [wenzhixin/multiple-select#448]
Actually, our setup has many records as the children. It would have been awesome, if the plugin only sent the parent optgroup value, instead of sending the value of all children; in case everything in that optgroup is selected. Any easy way to do this using the existing API?

Sorry if the description doesn't make sense. Here's a screenshot of what I am trying to achieve:

https://i.imgur.com/T0BeOlu.png

**Comment by wenzhixin** [comment]
```
$('select').multipleSelect('getSelects', 'text')
```

http://multiple-select-live.wenzhixin.net.cn/code/wenzhixin/493

**Comment by noc2spam** [comment]
Ahh, thanks a bunch man! Yupp that will work. :)
