### ISSUE TITLE
Cannot convert object to primitive value

### ISSUE THREAD

**Issue by AndriyYushko** [wenzhixin/multiple-select#474]
After update to 1.4.1 version get error Get error Uncaught TypeError: Cannot convert object to primitive value

**Comment by wenzhixin** [comment]
Please provide an [Online Example](http://multiple-select-live.wenzhixin.net.cn/) to show the problem, thanks!

**Comment by wenzhixin** [comment]
Our examples are working well: http://multiple-select.wenzhixin.net.cn/examples

**Comment by itajackass** [comment]
The error is referred to google maps if in the same page. I've already open a issues about this.
The message error is little different to my message cause i use firefox. in this case probably AndriyYushko use chrome
