### ISSUE TITLE
Refresh doesn't work on vue component

### ISSUE THREAD

**Issue by ramya-sc** [wenzhixin/multiple-select#475]
dynamic data is not being displayed in the dropdown and the refresh method isn't working either. 

myCode: 

`  <MultipleSelect
            ref="select"
            v-model="allTeamData"
            width="200"
            :options="options"
            @onClick=" selectTeamOption"
            @onCheckAll =" selectTeamOption"
          >
            <option
              v-for="data in allTeamData"
              v-bind:key="data"
              :value="data"
              >{{ data }}
            </option>
          </MultipleSelect>`

After data is returned from the api i'm calling the refresh method like 
 `this.$refs.select.refresh();`

**Comment by wenzhixin** [comment]
In your case, I recommend using data prop instead: http://multiple-select-live.wenzhixin.net.cn/code/wenzhixin/747

**Comment by wenzhixin** [comment]
If you want to use `refresh`, you need to call it in `this.$nextTick` method:
http://multiple-select-live.wenzhixin.net.cn/code/wenzhixin/748

**Comment by ramya-sc** [comment]
Thanks a lot @wenzhixin , it is working.

**Comment by wenzhixin** [comment]
You are welcome.
