### ISSUE TITLE
Bootstrap form-control class is broken

### ISSUE THREAD

**Issue by camohub** [wenzhixin/multiple-select#481]
Hi, I need to style multiple-select like bootstrap form-control. But if I set form-control class select element is broken, like on the screenshot. Is it possible to use form-control class or is it necessary to style it manually?
![Screenshot (16)](https://user-images.githubusercontent.com/8393426/66039874-5df6b000-e516-11e9-89d5-83a91ae76130.png)

**Comment by wenzhixin** [comment]
Fixed in #484

**Comment by wenzhixin** [comment]
Added themes css: https://github.com/wenzhixin/multiple-select/tree/develop/src/themes 
Example: http://multiple-select-live.wenzhixin.net.cn/code/wenzhixin/845
