### ISSUE TITLE
close method not working on vue component

### ISSUE THREAD

**Issue by ramya-sc** [wenzhixin/multiple-select#482]
How to close the dropdowns using close method in Vue component?
On click of date picker dropdown, I need to close all other dropdowns,
Assume I have some dropdown something like below,so, on click of date dropdown, i need to close the remaining dropdown
`<MultipleSelect
            ref="select" v-model="allData"
            name="months"
            width="200"
            :options="options"
            @onClick=" selectOption"
             @onCheckAll =" selectOption">
            <option value="option1">Option1</option>
                  <option value="option2">Option2</option>
                  <option value="option3">Option3</option>
          </MultipleSelect>
`
` <date-picker  v-on:panel-change="datepickerClicked" ></date-picker>`

//here is the below , what I am trying, but not working
`datepickerClicked() {
      this.$refs.select.close();
    //   $('#multiple').multipleSelect("close");
    },`

**Comment by wenzhixin** [comment]
http://multiple-select-live.wenzhixin.net.cn/code/wenzhixin/844

**Comment by ramya-sc** [comment]
It is not working
Description: Initially, assume I will click on team dropdown and when i click on datepicker dropdown , actually , the team dropdown should close, but rather than closing, the team dropdown and datepicker dropdrop are overlapping , and when i click outside of the dropdown should close all other dropdowns . please help me

**Comment by wenzhixin** [comment]
I think it's a bug of vue2-datepicker, because when you clicking the icon cannot trigger any event, a workaround for you: http://multiple-select-live.wenzhixin.net.cn/code/wenzhixin/847.

**Comment by ramya-sc** [comment]
Thanks a lot, it is working.
