### ISSUE TITLE
Multiple-select exceeded bootstrap cols

### ISSUE THREAD

**Issue by itajackass** [wenzhixin/multiple-select#485]
On bootstrap, multiple-select exceeded the cols div elements.

See attach.

![multiselectbug](https://user-images.githubusercontent.com/17260726/66142647-1e0ef600-e606-11e9-93a7-0911d97b418c.jpg)

I've solved with:

```
.ms-parent {
    width: 100% !important;
}
```

Maybe to be implemented to next release?

**Comment by wenzhixin** [comment]
Fixed #484, I think you can add `form-control` `class` to solve your problem.
