### ISSUE TITLE
single: true is selecting the first item by default

### ISSUE THREAD

**Issue by sharathdaniel** [wenzhixin/multiple-select#486]
I'm using the below code. Even the placeholder is not being displayed. Is there any i can prevent the first item not to be selected by default?

`$('select').multipleSelect({
      single: true,
	  filter: true,
	  placeholder: 'Select'
    })`

**Comment by wenzhixin** [comment]
You can add `multiple` attribute to do this: http://multiple-select-live.wenzhixin.net.cn/code/wenzhixin/867.

**Comment by sharathdaniel** [comment]
Ha, so that was so simple. Thanks!

**Comment by riteshkhatri** [comment]
if we add multiple attribute in select it will provide multiple select options.
How can we provide option to select only one option with place holder and not select default first element?
