### ISSUE TITLE
Filtering with Single doesn't hide opt groups

### ISSUE THREAD

**Issue by eXist73** [wenzhixin/multiple-select#487]
When using these options together:
**single: true**
**filter: true**

Filtering does not hide **optgroups** like it does in the example provided here: http://multiple-select.wenzhixin.net.cn/examples#filter.html

See image here to view issue:
https://i.gyazo.com/9db07c99acea0463ba75a0b0cbe1cf91.png

**Comment by wenzhixin** [comment]
Fixed in #488
http://multiple-select-live.wenzhixin.net.cn/code/wenzhixin/874
