### ISSUE TITLE
Single select overriding the Multiple select

### ISSUE THREAD

**Issue by ramya-sc** [wenzhixin/multiple-select#505]
Hi ,
I would like to mention that I am using Vue Component multiple select ( "multiple-select": "^1.4.1",)  example as below
`<MultipleSelect ref="select" v-model="select" width="200" :data="data  :options="options"
  @change="onChange" />`

Problem: When I run my application multiple-select is working fine for locally as I am attaching the screenshot 
![image](https://user-images.githubusercontent.com/47598314/67928324-bfc33c00-fbe0-11e9-8af7-9005d71c908c.png)
When I try to deploy the same code (multiple-select library) to the server ,single select is overriding the multiple select as I am attaching the screenshot below
![image](https://user-images.githubusercontent.com/47598314/67928500-2e07fe80-fbe1-11e9-82fe-e817f715ce05.png)

Can you please help me on this?

**Comment by wenzhixin** [comment]
Sorry for this, in our latest version, we updated to use the default behavior of `select` element.
http://multiple-select.wenzhixin.net.cn/docs/en/usage#via-javascript
http://multiple-select.wenzhixin.net.cn/docs/en/options#single
> if the select has not multiple attribute, this option will auto set to true.

```
<!-- Single Select -->
<select>
    <option value="1">January</option>
    ...
    <option value="12">December</option>
</select>

<!-- Multiple Select -->
<select multiple="multiple">
    <option value="1">January</option>
    ...
    <option value="12">December</option>
</select>
```

http://multiple-select.wenzhixin.net.cn/vue-examples#/single-row
http://multiple-select.wenzhixin.net.cn/vue-examples#/basic

In your case, you need to add `multiple` attribute to your multiple select.
