### ISSUE TITLE
Empty optgroup + selectAll event not working

### ISSUE THREAD

**Issue by jack1096** [wenzhixin/multiple-select#515]
This is existing example from website,

http://multiple-select-live.wenzhixin.net.cn/code/wenzhixin/947

Try this link. From Library select **version 1.5.2** and remove 

```
<option value="4" data-option="option4">Option 4</option>
<option value="5" data-option="option5">Option 5</option>
<option value="6" data-option="option6">Option 6</option>
```

this option from optgroup. now click on selectAll from dropdown.

 It **will not work in version 1.5.2** while it was **working in version 1.4.3**

**Comment by wenzhixin** [comment]
Fixed in #533
