### ISSUE TITLE
Responsive ms-drop / optgroups

### ISSUE THREAD

**Issue by ierpe** [wenzhixin/multiple-select#52]
Hi,
Your plugin is really cool thanks for your work! :)

There's one thing I could not achieve, maybe you can help me...
I'd like to have a "responsive" optgroups ul, that is, when the screen becomes too small, that the ms-drop / the optgroups li adapts its width and the optgroup elements "float:left" instead of being hidden....

![hidden-li](https://cloud.githubusercontent.com/assets/790992/2558822/da87ac0c-b75c-11e3-9b01-af5b20a5cfd7.png)

Do you think that would be possible?

**Comment by wenzhixin** [comment]
in the latest version, supports percent with.
