### ISSUE TITLE
Call function afterwards on already existing multipleSelect instance

### ISSUE THREAD

**Issue by vielhuber** [wenzhixin/multiple-select#522]
This works:

```js
let $select = $('.foo');
$select.multipleSelect();
$select.multipleSelect('getSelects'); // outputs correct values
```

This doesn't:

```js
$('.foo').multipleSelect();
$('.foo').multipleSelect('getSelects'); // error
```

How do I call a function (afterwards) on an already existing multiple select element where I don't have the dom element stored in a available ($select)?

**Comment by wenzhixin** [comment]
Please use `select.` instead.
```
$('select.foo').multipleSelect();
$('select.foo').multipleSelect('getSelects');
```

**Comment by wenzhixin** [comment]
Close this issue, if the problem exists reopen it and provide an [Online Example](https://live.bootstrap-table.com), thanks!
