### ISSUE TITLE
Bug on more than 200 itens

### ISSUE THREAD

**Issue by mvnp** [wenzhixin/multiple-select#528]
http://i.imgur.com/6EJiWoN.png

I have states with more than 200 cities and when I try to use the select scrool, it starts to flash and doesn't scroll down. Someone else had this error?

**Comment by wenzhixin** [comment]
Please provide an [Online Example](http://multiple-select-live.wenzhixin.net.cn/) to show your problem, thanks!

**Comment by kirubz** [comment]
Hi, 

Thanks for the nice plugin. 

Please find the example in the below link (flicker)

http://multiple-select-live.wenzhixin.net.cn/code/kirubz/1800

In this example, the dropdown is available inside hidden div.

Please let me know if you need any more information.

**Comment by kirubz** [comment]
Hi,
For the above problem, we hidden the control after initialized.
Please let me know if any solution available with hidden div.
Thanks

**Comment by wenzhixin** [comment]
Ref #526, need to use the `refresh` method.
http://multiple-select-live.wenzhixin.net.cn/code/wenzhixin/1921

**Comment by kirubz** [comment]
Thanks, now everything works fine.

**Comment by wenzhixin** [comment]
OK
