### ISSUE TITLE
Enable disable single option

### ISSUE THREAD

**Issue by itajackass** [wenzhixin/multiple-select#530]
Is there a method to enable/disable single options?

**Comment by wenzhixin** [comment]
You can use the jQuery method and [`refresh`](http://multiple-select.wenzhixin.net.cn/docs/en/methods#refresh) method to do this.
Online example: http://multiple-select-live.wenzhixin.net.cn/code/wenzhixin/1770

**Comment by itajackass** [comment]
Perfect!
