### ISSUE TITLE
Bahasa Melayu locale translation

### ISSUE THREAD

**Issue by wakjoko** [wenzhixin/multiple-select#539]
hi @wenzhixin 

i have made translation for malaysian language ms-MY.

i think your work is awesome to have.

**Comment by wenzhixin** [comment]
PR is welcome, like #537

**Comment by wenzhixin** [comment]
Any update? @wakjoko

**Comment by wakjoko** [comment]
Really sorry @wenzhixin , I'm stucked with another issue right now. I'll send pr asap

**Comment by wenzhixin** [comment]
OK, thanks!
