### ISSUE TITLE
Reset functionality not available

### ISSUE THREAD

**Issue by salewi** [wenzhixin/multiple-select#544]
Hello, I have been using multipleSelect for a while now. I am running into a problem following a client's ask. The clients wants the multiple select options to be populated by data from an Ajax call following a change in a particular field. However, I cannot get the mutlipleSelect to reset all the values inorder to populate it with the new values from an Ajax call. I've looked everywhere including trying to add a remove option on the core file, is there a way to reset/remove all the options values?

**Comment by wenzhixin** [comment]
You can use the [`data`](http://multiple-select.wenzhixin.net.cn/docs/en/options#data) option and the [`refreshOptions`](http://multiple-select.wenzhixin.net.cn/docs/en/methods#refreshoptions) method to solve your problem.

Online example: http://multiple-select-live.wenzhixin.net.cn/code/wenzhixin/2764

**Comment by salewi** [comment]
Awesome, thank you! I ended up using modifying the core files since we were using an old version of your plugin --

**Comment by wenzhixin** [comment]
You can use the `refresh` method if you are using an old version: http://multiple-select.wenzhixin.net.cn/examples#refresh.html
