### ISSUE TITLE
SetSelected all childrens with optGroup label in javascript

### ISSUE THREAD

**Issue by hebeto** [wenzhixin/multiple-select#545]
Hi.
I need setSelected all childrens with optGroup label in JavaScript.
Using $('#option').multipleSelect('setSelects', [values]); only set one childrens. I need check all childrens of one optGroup. I only have the optGroup label, i don´t have all childrens.

Can someone help me?
Thanks

**Comment by wenzhixin** [comment]
http://multiple-select-live.wenzhixin.net.cn/code/wenzhixin/2913
