### ISSUE TITLE
The Vue notation doesn't work

### ISSUE THREAD

**Issue by fengliting** [wenzhixin/multiple-select#585]
Local download project using Vue open, error reported
![image](https://user-images.githubusercontent.com/22767307/194843829-3359eec0-53f4-41ec-8577-93066a8f150d.png)
The vue example of the website also has the same error
![image](https://user-images.githubusercontent.com/22767307/194843924-d119573f-e5fa-419a-b877-f6d6a1b6829c.png)

**Comment by AnatoliyBerezin** [comment]
+1

**Comment by wenzhixin** [comment]
Fixed by https://github.com/wenzhixin/multiple-select/pull/602

https://multiple-select.wenzhixin.net.cn/vue-examples
