### ISSUE TITLE
Can't set placeholder for Single select

### ISSUE THREAD

**Issue by EvgeniyaSbitneva** [wenzhixin/multiple-select#586]
I've tried to set placeholder via html attribute and via js. For multiple select it works fine, but not for single.

**Comment by wenzhixin** [comment]
I use the `showClear` option and it working well: https://multiple-select-live.wenzhixin.net.cn/code/wenzhixin/15702

**Comment by n0xx** [comment]
Unfortunately it does not work on single select.
