### ISSUE TITLE
onFilter event retrieves text only lowercase format

### ISSUE THREAD

**Issue by Faxriddin077** [wenzhixin/multiple-select#607]
Hi everyone
I used onFilter event with filter:

$('select').multipleSelect({
                filter: true,
               onFilter: function (text) {
                    console.log(text)
                }
            })

that text variable always returns as lowercase. For example: 
Typed: "Hello World"      Result: "hello world"
Typed: "Hello WORLD"      Result: "hello world"
Typed: "HELLO World"      Result: "hello world"

Can you help me with that problem?

**Comment by wenzhixin** [comment]
Fixed in #609
