### ISSUE TITLE
Enable/disable options ?

### ISSUE THREAD

**Issue by p-wieser** [wenzhixin/multiple-select#617]
Hi,
Maybe I do not know how to read your documentation - which is amazing by the fact ! -, or maybe I badly read it,  but I do not find how to enable/disable an option.
My use case is that not all options can be selected, but it exists some allowed combinations that I want respect in the UI, and not wait until the server to check that..
Any tip, please ?
Best regards
Pierre

**Comment by p-wieser** [comment]
Hello again,
I eventually enable/disable individual options via jQuery and an index-based selector. So I fulfill my requirement.
But it bellieve that this should be a multipleSelect method, doesn't it ?
Best regards

**Comment by wenzhixin** [comment]
There's no method to update an option, but you can modify the data and refresh the `select`.
https://multiple-select-live.wenzhixin.net.cn/code/wenzhixin/16913
