### ISSUE TITLE
Single-select with Optgroups: problems

### ISSUE THREAD

**Issue by pkalwar** [wenzhixin/multiple-select#84]
Hello,

The plugin shows issues when using optgroups with single-select (single:true), as follows:

- Shows checkboxes for opt-groups (should be none, not even radio-box)
- I also see if there are multiple single-select dropdowns on one page, then selection is lost from one dropdown if i select an option in another dropdown. 

Thanks, Praveen

**Comment by wenzhixin** [comment]
Fixed: http://jsfiddle.net/wenyi/knbdm5hu/18/
